'use client';
import React from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxRev, SxCompare } from './ScriptOnRevisions';
import { useLocale } from '@/lib/i18n';
const SC=`.dvt .cg{flex:1;display:grid;grid-template-columns:280px 1fr;gap:14px;min-height:0}.dvt .tl2{background:var(--panel);border:1px solid var(--hair);border-radius:14px;padding:8px;overflow:auto}.dvt .rr{display:flex;gap:10px;padding:12px;border-radius:10px;width:100%;text-align:left;background:none;border:1px solid transparent;cursor:pointer}.dvt .rr.on{background:rgba(198,164,99,.08);border-color:rgba(198,164,99,.35)}.dvt .rd{width:11px;height:11px;border-radius:50%;flex:none;margin-top:3px}.dvt .rl3{font-size:12.5px;font-weight:700;color:var(--cream)}.dvt .ra{font-size:10.5px;color:var(--mute);margin-top:2px}.dvt .rs{font-size:10.5px;color:var(--faint);margin-top:3px}.dvt .cmp{background:var(--panel);border:1px solid var(--hair);border-radius:14px;display:flex;flex-direction:column;overflow:hidden}.dvt .ch{padding:12px;border-bottom:1px solid var(--hair);display:flex;gap:10px;align-items:center}.dvt .cc{flex:1;display:grid;grid-template-columns:1fr 1fr}.dvt .col{padding:14px;overflow:auto}.dvt .col+.col{border-left:1px solid var(--hair)}.dvt .sheet{background:var(--paper);color:var(--ink);border-radius:8px;padding:16px;font-family:'Courier Prime',monospace;font-size:11px;line-height:1.8}.dvt .sl{display:block}.dvt .add{background:rgba(87,179,104,.3)}.dvt .del{background:rgba(229,99,95,.26);text-decoration:line-through;opacity:.65}`;
type P={title:string;meta:string;revisions:SxRev[];activeToId?:string;onSelect:(id:string)=>void;compare:SxCompare;loading?:boolean;onAction:(k:string)=>void;onNav:(k:string)=>void;onBack:()=>void;toast?:string|null};
export default function ScriptOnRevisionsTablet(p:P){const{dir,t}=useLocale();const c=p.compare;return(<div className="dvt" dir={dir}><style dangerouslySetInnerHTML={{__html:T_CSS+SC}}/>
<div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{t('Revisions & Compare')}</div></div><div className="seg">{SEG5.map(([k,l,d])=><button key={k} className="segtab" onClick={()=>p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d}/></svg>{t(l)}</button>)}</div><button className="btn gold" onClick={()=>p.onAction('new')}><svg className="ico" viewBox="0 0 24 24" style={{stroke:'#1a1509'}}><path d="M12 5v14M5 12h14"/></svg>{t('New revision')}</button></div>
<div className="content"><div className="cg"><div className="tl2">{p.revisions.map(r=><button key={r.id} className={'rr'+(r.id===p.activeToId?' on':'')} onClick={()=>p.onSelect(r.id)}><span className="rd" style={{background:r.color}}/><div><div className="rl3">{r.label}{r.active?' — '+t('current'):''}</div><div className="ra">{r.author} · {r.date}</div><div className="rs">{r.summary}</div></div></button>)}</div>
<div className="cmp">{c?(<><div className="ch"><span className="pill" style={{background:c.fromColor+'28',color:c.fromColor}}><span className="d" style={{background:c.fromColor}}/>{c.fromLabel.toUpperCase()}</span><svg className="ico" viewBox="0 0 24 24" style={{color:'var(--faint)'}}><path d="M5 12h14M13 6l6 6-6 6"/></svg><span className="pill" style={{background:c.toColor+'28',color:c.toColor}}><span className="d" style={{background:c.toColor}}/>{c.toLabel.toUpperCase()}</span></div><div className="cc"><div className="col"><div className="sheet">{c.fromLines.map((l,i)=><span className={'sl '+l.cls} key={i}>{l.t||' '}</span>)}</div></div><div className="col"><div className="sheet">{c.toLines.map((l,i)=><span className={'sl '+l.cls} key={i}>{l.t||' '}</span>)}</div></div></div></>):<div style={{flex:1,display:'grid',placeItems:'center',color:'var(--faint)',fontSize:12.5}}>{t('Select a revision to compare.')}</div>}</div></div></div>
{p.toast&&<div className="toast">{p.toast}</div>}</div>);}
