'use client';
import React from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxNote, SxThread } from './ScriptOnNotes';
import { useLocale } from '@/lib/i18n';
const SC=`.dvt .ng{flex:1;display:grid;grid-template-columns:1.2fr 1fr;gap:14px;min-height:0}.dvt .nl{background:var(--panel);border:1px solid var(--hair);border-radius:14px;overflow:auto}.dvt .nr{display:flex;gap:11px;padding:13px 15px;border-bottom:1px solid var(--hair);width:100%;text-align:left;background:none;border-left:none;border-right:none;border-top:none;cursor:pointer}.dvt .nr.on{background:rgba(198,164,99,.08)}.dvt .av{width:32px;height:32px;border-radius:50%;flex:none;display:grid;place-items:center;font-size:11px;font-weight:800;color:#fff}.dvt .nau{font-size:12.5px;font-weight:700;color:var(--cream)}.dvt .nsc{font-size:10px;font-weight:700;color:var(--gold2);background:rgba(198,164,99,.13);padding:2px 6px;border-radius:6px;margin-left:6px}.dvt .ntx{font-size:11.5px;color:var(--mute);margin-top:4px;line-height:1.4}.dvt .th{background:var(--panel);border:1px solid var(--hair);border-radius:14px;display:flex;flex-direction:column;overflow:hidden}.dvt .thh{padding:12px 15px;border-bottom:1px solid var(--hair);display:flex;align-items:center;gap:8px}.dvt .thb{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:11px}.dvt .bub{display:flex;gap:9px}.dvt .bx{flex:1;background:#1b1e25;border:1px solid var(--hair);border-radius:11px;padding:10px 12px;font-size:12px;color:var(--text);line-height:1.4}.dvt .bx.doc{background:rgba(198,164,99,.08);border-color:rgba(198,164,99,.3)}`;
type P={title:string;meta:string;filters:string[];activeFilter:string;onFilter:(f:string)=>void;notes:SxNote[];activeId?:string;onSelect:(id:string)=>void;thread:SxThread;onAction:(k:string)=>void;onNav:(k:string)=>void;onBack:()=>void;toast?:string|null};
export default function ScriptOnNotesTablet(p:P){const{dir,t:tr}=useLocale();const t=p.thread;return(<div className="dvt" dir={dir}><style dangerouslySetInnerHTML={{__html:T_CSS+SC}}/>
<div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{tr('Notes & Collaboration')}</div></div><div className="seg">{SEG5.map(([k,l,d])=><button key={k} className="segtab" onClick={()=>p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d}/></svg>{tr(l)}</button>)}</div><button className="btn gold" onClick={()=>p.onAction('new')}><svg className="ico" viewBox="0 0 24 24" style={{stroke:'#1a1509'}}><path d="M12 5v14M5 12h14"/></svg>{tr('New note')}</button></div>
<div className="content"><div className="chips">{p.filters.map(f=><button key={f} className={'chip'+(f===p.activeFilter?' on':'')} onClick={()=>p.onFilter(f)}>{f}</button>)}</div>
<div className="ng"><div className="nl">{p.notes.map(n=><button key={n.id} className={'nr'+(n.id===p.activeId?' on':'')} onClick={()=>p.onSelect(n.id)}><div className="av" style={{background:n.color}}>{n.av}</div><div style={{flex:1}}><span className="nau">{n.author.split(' · ')[0]}</span><span className="nsc">{n.scene}</span><div className="ntx">{n.text}</div></div></button>)}</div>
<div className="th">{t?(<><div className="thh"><span className="nsc">{t.scene}</span><span className={'badge '+t.badgeClass}>{t.badge}</span></div><div className="thb">{t.bubbles.map((b,i)=><div className={'bub'+(b.doc?' doc':'')} key={i}><div className="av" style={{background:b.doc?'linear-gradient(160deg,#E6D2A2,#C6A463)':b.color,color:b.doc?'#1a1509':'#fff'}}>{b.av}</div><div className="bx">{b.text}</div></div>)}</div></>):<div style={{flex:1,display:'grid',placeItems:'center',color:'var(--faint)',fontSize:12.5}}>{tr('Select a note.')}</div>}</div></div></div>
{p.toast&&<div className="toast">{p.toast}</div>}</div>);}
