'use client';
import React from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxGauge, SxCoverage, SxDiag, SxTab } from './ScriptOnDoctor';
import { useLocale } from '@/lib/i18n';
const SC = `.dvt .gauges{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.dvt .g{background:linear-gradient(180deg,#16191f,#131519);border:1px solid var(--hair);border-radius:12px;padding:12px}.dvt .gl{font-size:10px;color:var(--faint);font-weight:600}.dvt .gv{font-size:20px;font-weight:800;margin-top:5px}.dvt .dtabs{display:flex;gap:7px}.dvt .dtab{padding:8px 13px;border-radius:10px;font-size:12.5px;font-weight:600;color:var(--mute);background:#171a20;border:1px solid var(--hair);cursor:pointer}.dvt .dtab.on{background:rgba(198,164,99,.14);border-color:rgba(198,164,99,.45);color:var(--gold2)}.dvt .drg{flex:1;display:grid;grid-template-columns:1.7fr 1fr;gap:14px;min-height:0}.dvt .report{background:var(--panel);border:1px solid var(--hair);border-radius:14px;padding:18px;overflow:auto;display:flex;flex-direction:column;gap:13px}.dvt .rsec h3{font-size:10.5px;font-weight:700;letter-spacing:1.1px;color:var(--gold);margin-bottom:6px}.dvt .logline{font-size:15px;line-height:1.5;color:var(--cream);font-weight:500}.dvt .synop{font-size:12.5px;line-height:1.6;color:var(--mute)}.dvt .pt{display:flex;gap:9px;font-size:12px;line-height:1.4;margin-bottom:6px}.dvt .actbar{display:flex;align-items:center;gap:9px;font-size:12px;margin-bottom:8px}.dvt .al{width:42px;color:var(--faint);font-weight:600}.dvt .m2{flex:1;height:7px;border-radius:5px;background:#23262e;overflow:hidden}.dvt .m2 i{display:block;height:100%}.dvt .empty{flex:1;display:grid;place-items:center;color:var(--faint);font-size:12.5px;text-align:center;padding:20px}`;
type P = { title: string; revisionLabel?: string; revisionColor?: string; meta: string; gauges: SxGauge[]; activeTab: SxTab; onTab: (t: SxTab) => void; coverage: SxCoverage; covLoading?: boolean; onGenerate: () => void; diagnostics: SxDiag[] | null; diagLoading?: boolean; onRunDiag: () => void; actHealth: { label: string; pct: number; tone: string; note: string }[]; onAction: (k: string) => void; onNav: (k: string) => void; onBack: () => void; toast?: string | null };
const PI: any = { good: { c: 'var(--green)', s: '✓' }, warn: { c: 'var(--amber)', s: '!' }, bad: { c: 'var(--red)', s: '×' } };
export default function ScriptOnDoctorTablet(p: P) {
  const { dir, t } = useLocale();
  const cov = p.coverage; const rc = p.revisionColor || '#5b8def';
  return (<div className="dvt" dir={dir}><style dangerouslySetInnerHTML={{ __html: T_CSS + SC }} />
    <div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{p.title}</div><span className="pill" style={{ background: rc + '28', color: rc }}><span className="d" style={{ background: rc }} />{(p.revisionLabel || 'DRAFT').toUpperCase()}</span></div>
      <div className="seg">{SEG5.map(([k, l, d]) => <button key={k} className={'segtab' + (k === 'doctor' ? ' on' : '')} onClick={() => k !== 'doctor' && p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d} /></svg>{t(l)}</button>)}</div>
      <button className="btn gold" onClick={p.onRunDiag}><svg className="ico" viewBox="0 0 24 24" style={{ stroke: '#1a1509' }}><path d="M12 3l1.9 5.6L19.5 9l-4.5 3.3L16.8 18 12 14.7 7.2 18l1.8-5.7L4.5 9z" /></svg>{t('Run diagnostic')}</button></div>
    <div className="content"><div><div className="h1">{t('Script Doctor')}</div><div className="sub">{t('Coverage & diagnostics — every note cites a scene.')}</div></div>
      <div className="gauges">{p.gauges.map((g, i) => <div className="g" key={i}><div className="gl">{g.label}</div><div className="gv" style={{ color: g.color, fontSize: g.value.length > 3 ? 14 : 20, paddingTop: g.value.length > 3 ? 4 : 0 }}>{g.value}</div><div className="mtr" style={{ marginTop: 8 }}><i style={{ width: g.pct + '%', background: g.color }} /></div></div>)}</div>
      <div className="dtabs">{(['Coverage', 'Diagnostics', 'Rewrite', 'Compare'] as SxTab[]).map((tb) => <button key={tb} className={'dtab' + (p.activeTab === tb ? ' on' : '')} onClick={() => p.onTab(tb)}>{tb === 'Rewrite' ? t('Rewrite slate') : t(tb)}</button>)}</div>
      <div className="drg"><div className="report">
        {p.activeTab === 'Coverage' && (cov ? (<>{cov.logline && <div className="rsec"><h3>{t('LOGLINE')}</h3><div className="logline">{cov.logline}</div></div>}{cov.synopsis && <div className="rsec"><h3>{t('SYNOPSIS')}</h3><div className="synop">{cov.synopsis}</div></div>}<div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}><div className="rsec"><h3>{t('STRENGTHS')}</h3>{cov.strengths.map((x, i) => <div className="pt" key={i}><span style={{ color: PI[x.tone].c }}>{PI[x.tone].s}</span>{x.text}</div>)}</div><div className="rsec"><h3>{t('CONCERNS')}</h3>{cov.concerns.map((x, i) => <div className="pt" key={i}><span style={{ color: PI[x.tone].c }}>{PI[x.tone].s}</span>{x.text}</div>)}</div></div>{cov.comps.length > 0 && <div className="rsec"><h3>{t('COMPARABLES')}</h3><div className="chips">{cov.comps.map((c, i) => <span className="chip on" key={i}>{c}</span>)}</div></div>}</>) : <div className="empty">{t('No coverage yet.')}<br /><br /><button className="btn gold" onClick={p.onGenerate}>{t('Generate coverage')}</button></div>)}
        {p.activeTab === 'Diagnostics' && (p.diagnostics && p.diagnostics.length ? p.diagnostics.map((d, i) => <div className="rsec" key={i} style={{ borderTop: i ? '1px solid var(--hair)' : 'none', paddingTop: i ? 10 : 0 }}><h3 style={{ color: 'var(--cream)' }}>{d.sceneNumber}. {d.slugline} <span className={'badge ' + (d.verdict === 'CUT' ? 'red' : d.verdict === 'KEEP' ? 'green' : 'amber')}>{d.verdict}</span></h3><div className="synop">{[d.objective && t('Wants') + ': ' + d.objective, d.obstacle && t('Obstacle') + ': ' + d.obstacle].filter(Boolean).join(' · ')}</div></div>) : <div className="empty">{t('Run diagnostics to read every scene.')}<br /><br /><button className="btn gold" onClick={p.onRunDiag}>{t('Run diagnostics')}</button></div>)}
        {(p.activeTab === 'Rewrite' || p.activeTab === 'Compare') && <div className="empty">{p.activeTab === 'Compare' ? t('Open the full Revisions & Compare screen.') : t('Rewrite slate ships in engine phase P2.')}{p.activeTab === 'Compare' && <><br /><br /><button className="btn gold" onClick={() => p.onAction('compare')}>{t('Compare revisions')}</button></>}</div>}
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><div className="card"><div className="pc-h"><span className="t">{t('Act health')}</span><span className="eyebrow">{t('PACE')}</span></div>{p.actHealth.map((a, i) => <div className="actbar" key={i}><span className="al">{a.label}</span><span className="m2"><i style={{ width: a.pct + '%', background: a.tone }} /></span></div>)}</div>
        <div className="card" style={{ flex: 1 }}><div className="pc-h"><span className="t">{t('Doctor actions')}</span></div><div className="qa"><button className="tile" onClick={() => p.onAction('diagnose')}><div className="ti"><svg className="ico" viewBox="0 0 24 24"><path d="M3 12h4l2 6 4-14 2 8h6" /></svg></div><div className="tt">{t('Diagnose')}</div></button><button className="tile" onClick={() => p.onAction('budgetfit')}><div className="ti"><svg className="ico" viewBox="0 0 24 24"><path d="M12 1v22M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6" /></svg></div><div className="tt">{t('Budget-fit')}</div></button><button className="tile" onClick={() => p.onAction('compare')}><div className="ti"><svg className="ico" viewBox="0 0 24 24"><path d="M16 3l5 5-5 5M21 8H9M8 21l-5-5 5-5M3 16h12" /></svg></div><div className="tt">{t('Compare')}</div></button><button className="tile" onClick={() => p.onAction('rewrite')}><div className="ti"><svg className="ico" viewBox="0 0 24 24"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 013 3L7 19l-4 1 1-4z" /></svg></div><div className="tt">{t('Rewrite')}</div></button></div></div></div>
      </div></div>
    {p.toast && <div className="toast">{p.toast}</div>}
  </div>);
}
