'use client';
import React from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxRun } from './ScriptOnSettings';
import { useLocale } from '@/lib/i18n';
const SC=`.dvt .sg{flex:1;display:grid;grid-template-columns:200px 1fr;gap:14px;min-height:0}.dvt .sn{display:flex;flex-direction:column;gap:3px}.dvt .sni{display:flex;align-items:center;gap:9px;padding:10px 12px;border-radius:10px;font-size:12.5px;font-weight:600;color:var(--mute)}.dvt .sni.on{background:rgba(198,164,99,.13);color:var(--gold2)}.dvt .sm{overflow:auto;display:flex;flex-direction:column;gap:12px}.dvt .three{display:grid;grid-template-columns:1.3fr 1fr 1fr;gap:11px}.dvt .gt{flex:1;background:var(--panel);border:1px solid var(--hair);border-radius:13px;overflow:hidden}.dvt .gth,.dvt .gtr{display:grid;grid-template-columns:1.3fr 1.4fr .8fr 1fr .8fr;gap:8px;padding:10px 14px;align-items:center}.dvt .gth{border-bottom:1px solid var(--hair);font-size:10px;font-weight:700;color:var(--faint);background:#101319}.dvt .gtr{border-bottom:1px solid var(--hair);font-size:11.5px}.dvt .gsf{font-weight:600;color:var(--cream)}.dvt .gm{color:var(--mute);font-family:'Courier Prime',monospace;font-size:10.5px}.dvt .tg{width:42px;height:24px;border-radius:999px;background:linear-gradient(90deg,var(--gold),var(--gold2));position:relative}.dvt .tg:after{content:"";position:absolute;width:18px;height:18px;border-radius:50%;background:#fff;top:3px;right:3px}.dvt .sl{height:6px;border-radius:4px;background:#23262e;position:relative;margin:12px 0 6px}.dvt .sl i{position:absolute;left:0;top:0;bottom:0;border-radius:4px;background:linear-gradient(90deg,var(--gold),var(--gold2))}`;
type P={companyName:string;model:string;promptSet:string;confidence:number;humanApproval:boolean;runs:SxRun[];runsMeta:string;onAction:(k:string)=>void;onNav:(k:string)=>void;onBack:()=>void;toast?:string|null};
export default function ScriptOnSettingsTablet(p:P){const{dir,t}=useLocale();return(<div className="dvt" dir={dir}><style dangerouslySetInnerHTML={{__html:T_CSS+SC}}/>
<div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{p.companyName}</div><span className="meta">{t('Settings · governance')}</span></div><div className="seg">{SEG5.map(([k,l,d])=><button key={k} className="segtab" onClick={()=>p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d}/></svg>{t(l)}</button>)}</div><button className="btn gold" onClick={()=>p.onAction('save')}><svg className="ico" viewBox="0 0 24 24" style={{stroke:'#1a1509'}}><path d="M20 6L9 17l-5-5"/></svg>{t('Save')}</button></div>
<div className="content"><div><div className="h1">{t('AI Governance')}</div><div className="sub">{t('One gateway, one audit trail.')}</div></div>
<div className="sg"><div className="sn"><div className="sni">{t('Workspace')}</div><div className="sni on"><svg className="ico" viewBox="0 0 24 24"><path d="M12 3l1.9 5.6L19.5 9l-4.5 3.3L16.8 18 12 14.7 7.2 18l1.8-5.7L4.5 9z"/></svg>{t('AI Governance')}</div><div className="sni">{t('Members')}</div><div className="sni">{t('Tenancy')}</div><div className="sni">{t('Integrations')}</div><div className="sni">{t('Billing')}</div></div>
<div className="sm"><div className="three"><div className="card"><div className="eyebrow">{t('ACTIVE MODEL')}</div><div style={{fontSize:14,fontWeight:700,color:'var(--cream)',fontFamily:"'Courier Prime',monospace"}}>{p.model}</div><div className="sub" style={{fontSize:11}}>{p.promptSet}</div></div><div className="card"><div className="eyebrow">{t('CONFIDENCE GATE')}</div><div className="sl"><i style={{width:Math.round(p.confidence*100)+'%'}}/></div><div className="sub" style={{fontSize:11}}>{t('Hold <')} <b style={{color:'var(--gold2)'}}>{p.confidence.toFixed(2)}</b> {t('as PENDING')}</div></div><div className="card"><div className="eyebrow">{t('HUMAN APPROVAL')}</div><div style={{display:'flex',alignItems:'center',gap:10}}><span className="tg"/><span style={{fontSize:12,color:'var(--cream)',fontWeight:600}}>{p.humanApproval?t('Required'):t('Off')}</span></div></div></div>
<div className="eyebrow">{t('AiRun AUDIT LOG')} · {p.runsMeta}</div><div className="gt"><div className="gth"><span>{t('SURFACE')}</span><span>{t('MODEL')}</span><span>{t('TOKENS')}</span><span>{t('CONF')}</span><span>{t('STATUS')}</span></div>{p.runs.map((r,i)=><div className="gtr" key={i}><span className="gsf">{t(r.surface)}</span><span className="gm">{r.model}</span><span className="gm">{r.tokens}</span><span className="gm">{r.conf.toFixed(2)}</span><span className={'badge '+r.statusClass}>{r.status}</span></div>)}</div></div></div></div>
{p.toast&&<div className="toast">{p.toast}</div>}</div>);}
