'use client';
import React from 'react';
import { M_CSS, TAB5 } from './deviceCss';
import type { SxComp, SxFcast, SxRoi, SxDecision } from './ScriptOnGreenlight';
import { useLocale } from '@/lib/i18n';
const SC = `.dvm .comp{display:flex;align-items:center;gap:9px;padding:9px 0;border-top:1px solid var(--hair)}.dvm .comp:first-of-type{border-top:none}.dvm .cname{flex:1;font-size:12px;font-weight:600;color:var(--cream)}.dvm .cbar{width:64px;height:5px;border-radius:4px;background:#23262e;overflow:hidden}.dvm .cbar i{display:block;height:100%;background:linear-gradient(90deg,var(--gold),var(--gold2))}.dvm .cgr{font-size:11px;color:var(--mute)}.dvm .fwin{display:flex;align-items:center;gap:9px;padding:8px 0;border-top:1px solid var(--hair);font-size:12px}.dvm .fwin:first-of-type{border-top:none}.dvm .fl{width:74px;color:var(--faint);font-weight:600}.dvm .fb{flex:1;height:7px;border-radius:5px;background:#23262e;overflow:hidden}.dvm .fb i{display:block;height:100%;border-radius:5px}.dvm .fv{width:54px;text-align:end;font-weight:700;color:var(--cream)}.dvm .ring{width:108px;height:108px;border-radius:50%;display:grid;place-items:center;position:relative;margin:2px auto}.dvm .ring:before{content:"";position:absolute;inset:10px;border-radius:50%;background:var(--panel)}.dvm .rv{position:relative;font-size:26px;font-weight:800;color:var(--cream)}.dvm .rs{position:relative;font-size:9px;color:var(--faint)}.dvm .roi{width:100%;border-collapse:collapse}.dvm .roi th,.dvm .roi td{text-align:end;padding:7px 5px;font-size:11.5px;border-bottom:1px solid var(--hair)}.dvm .roi th{color:var(--faint);font-weight:700;font-size:9.5px}.dvm .roi td:first-child,.dvm .roi th:first-child{text-align:start;color:var(--cream);font-weight:600}.dvm .ql{font-size:11px;font-weight:700;letter-spacing:.5px;color:var(--gold)}.dvm .qa2{font-size:12px;color:var(--text);line-height:1.45;margin:5px 0}.dvm .qmeter{height:5px;border-radius:4px;background:#23262e;overflow:hidden}.dvm .qmeter i{display:block;height:100%;background:linear-gradient(90deg,var(--gold),var(--gold2))}.dvm .sc{display:flex;align-items:center;gap:9px;padding:8px 0;border-top:1px solid var(--hair)}.dvm .sc:first-of-type{border-top:none}.dvm .scn{width:96px;font-size:11.5px;font-weight:600;color:var(--cream)}.dvm .scbar{flex:1;height:6px;border-radius:5px;background:#23262e;overflow:hidden}.dvm .scbar i{display:block;height:100%;background:linear-gradient(90deg,var(--gold),var(--gold2))}.dvm .scv{width:38px;text-align:end;font-size:11.5px;font-weight:700;color:var(--cream)}.dvm .costrow{display:flex;align-items:center;gap:9px;padding:9px 0;border-top:1px solid var(--hair)}.dvm .costrow:first-of-type{border-top:none}.dvm .ci{flex:1}.dvm .cii{font-size:12px;font-weight:600;color:var(--cream)}.dvm .cin{font-size:10.5px;color:var(--faint)}.dvm .cs{font-size:13px;font-weight:800;color:var(--green)}.dvm .verdict{display:inline-flex;padding:6px 13px;border-radius:999px;font-size:12px;font-weight:800;letter-spacing:.5px}.dvm .memo{font-size:12px;line-height:1.6;color:var(--text)}`;
const appealPct = (t: string) => { const u = String(t || '').toLowerCase(); if (u.includes('very high') || u.startsWith('high')) return 88; if (u.includes('med-high')) return 72; if (u.includes('med')) return 56; if (u.includes('low-med')) return 40; if (u.includes('low')) return 26; return 50; };
const vColor = (v: string) => { const u = String(v || '').toUpperCase(); if (u.includes('GREEN') || u === 'GO') return 'var(--green)'; if (u.includes('PASS') || u.includes('HOLD')) return 'var(--red)'; return 'var(--amber)'; };
type P = { title: string; meta: string; mode: string; onTab: (k: string) => void; comps: SxComp[]; forecast: SxFcast[]; prob: { pct: number; verdict: string; note: string }; roi: SxRoi[]; prescription: string; decision: SxDecision; onNav: (k: string) => void; onBack: () => void; onAction: (k: string) => void; toast?: string | null };
export default function ScriptOnGreenlightMobile(p: P) {
  const { dir, t } = useLocale();
  const ring = `conic-gradient(var(--gold) 0 ${p.prob.pct}%,#23262e ${p.prob.pct}% 100%)`; const m = p.mode; const dec = p.decision;
  return (<div className="dvm" dir={dir}><style dangerouslySetInnerHTML={{ __html: M_CSS + SC }} />
    <div className="sb"><span>9:41</span><div className="r"><svg viewBox="0 0 24 24"><path d="M2 20h.01M6 20v-4M10 20v-8M14 20V8M18 20V4" /></svg><svg viewBox="0 0 24 24"><rect x="2" y="7" width="18" height="10" rx="2" /></svg></div></div>
    <div className="mtop"><button className="dr" onClick={p.onBack}>TFM</button><div className="ti"><div className="t1">{t('Greenlight')}</div><div className="t2">{p.meta}</div></div></div>
    <div className="scroll"><div className="chips"><button className={'chip' + (m === 'market' ? ' on' : '')} onClick={() => p.onTab('market')}>{t('Market')}</button><button className={'chip' + (m === 'audience' ? ' on' : '')} onClick={() => p.onTab('audience')}>{t('Audience')}</button><button className={'chip' + (m === 'cost' ? ' on' : '')} onClick={() => p.onTab('cost')}>{t('Cost')}</button><button className={'chip' + (m === 'decision' ? ' on' : '')} onClick={() => p.onTab('decision')}>{t('Decision')}</button></div>
      {m === 'market' && <>
        <div className="card"><div className="pc-h"><span className="t">{t('Greenlight probability')}</span><span className="badge amber">{p.prob.verdict}</span></div><div className="ring" style={{ background: ring }}><span className="rv">{p.prob.pct}%</span><span className="rs">{t('P(greenlight)')}</span></div></div>
        <div className="card"><div className="pc-h"><span className="t">{t('Forecast')}</span><span className="eyebrow">{t('P50 · 80% BAND')}</span></div>{p.forecast.map((f, i) => <div className="fwin" key={i}><span className="fl">{t(f.label)}</span><span className="fb"><i style={{ width: f.pct + '%', background: f.color }} /></span><span className="fv" style={f.gold ? { color: 'var(--gold2)' } : {}}>{f.value}</span></div>)}</div>
        <div className="card"><div className="pc-h"><span className="t">{t('Comparables')}</span><span className="eyebrow">{t('SIMILARITY')}</span></div>{p.comps.map((c, i) => <div className="comp" key={i}><span className="cname">{c.name}</span><span className="cbar"><i style={{ width: c.sim + '%' }} /></span><span className="cgr">{c.sim}%</span></div>)}</div>
        <div className="card"><div className="pc-h"><span className="t">{t('Predict → re-cost')}</span></div><table className="roi"><thead><tr><th>{t('Case')}</th><th>{t('Rev')}</th><th>{t('Margin')}</th><th>{t('ROI')}</th></tr></thead><tbody>{p.roi.map((r, i) => <tr key={i}><td style={r.tone ? { color: r.tone } : {}}>{t(r.case)}</td><td>{r.rev}</td><td style={r.tone ? { color: r.tone } : {}}>{r.margin}</td><td>{r.roi}</td></tr>)}</tbody></table></div></>}
      {m === 'audience' && dec.audience.map((q, i) => <div className="card" key={i}><div className="ql">{t(q.quadrant)}</div><div className="qa2">{t(q.appeal)}</div><div className="qmeter"><i style={{ width: appealPct(q.appeal) + '%' }} /></div></div>)}
      {m === 'cost' && <div className="card"><div className="pc-h"><span className="t">{t('Cost opportunities')}</span><span className="eyebrow">{t('ON THE NEGATIVE')}</span></div>{dec.costOps.map((c, i) => <div className="costrow" key={i}><div className="ci"><div className="cii">{t(c.item)}</div>{c.note && <div className="cin">{t(c.note)}</div>}</div><div className="cs">{c.saving}</div></div>)}</div>}
      {m === 'decision' && <>
        <div className="card"><div className="pc-h"><span className="t">{t('Verdict')}</span><span className="badge amber">{dec.probability}% P</span></div><div style={{ display: 'flex', justifyContent: 'center', padding: '4px 0' }}><span className="verdict" style={{ color: vColor(dec.verdict), background: 'rgba(224,162,59,.16)' }}>{dec.verdict}</span></div><div className="memo">{t(dec.memo)}</div></div>
        <div className="card"><div className="pc-h"><span className="t">{t('Scorecard')}</span><span className="eyebrow">{t('WEIGHTED')}</span></div>{dec.scorecard.map((s, i) => <div className="sc" key={i}><span className="scn">{t(s.criterion)}</span><span className="scbar"><i style={{ width: (Number(s.score) || 0) * 10 + '%' }} /></span><span className="scv">{s.score}/10</span></div>)}</div></>}
    </div>
    <div className="tabbar">{TAB5.map(([k, l, d]) => <button key={k} className={'tab' + (k === 'greenlight' ? ' on' : '')} onClick={() => p.onNav(k)}><div className="b"><svg className="ico" viewBox="0 0 24 24"><path d={d} /></svg></div>{t(l)}</button>)}</div>
    {p.toast && <div className="toast">{p.toast}</div>}</div>);
}
