CREATE TYPE "ImportSource" AS ENUM ('MANUAL','SCHEDULED_GMAIL','DOCUMENT_OCR','BULK_IMPORT');
ALTER TYPE "Activity" ADD VALUE IF NOT EXISTS 'PRODUCTION_SERVICE';
ALTER TYPE "Activity" ADD VALUE IF NOT EXISTS 'BOOK_DESIGN';
ALTER TYPE "Activity" ADD VALUE IF NOT EXISTS 'WEB_DESIGN';
ALTER TYPE "Activity" ADD VALUE IF NOT EXISTS 'EVENTS';
ALTER TABLE "expenses" ADD COLUMN "invoiceNumber" TEXT;
ALTER TABLE "expenses" ADD COLUMN "invoiceDate" TIMESTAMP(3);
ALTER TABLE "expenses" ADD COLUMN "dueDate" TIMESTAMP(3);
ALTER TABLE "expenses" ADD COLUMN "sourceUrl" TEXT;
ALTER TABLE "expenses" ADD COLUMN "sourceRef" TEXT;
ALTER TABLE "expenses" ADD COLUMN "importBatchId" TEXT;
ALTER TABLE "expenses" ADD COLUMN "importedAt" TIMESTAMP(3);
ALTER TABLE "expenses" ADD COLUMN "reviewedById" TEXT;
ALTER TABLE "expenses" ADD COLUMN "reviewedAt" TIMESTAMP(3);
ALTER TABLE "expenses" ADD COLUMN "rejectionReason" TEXT;
ALTER TABLE "expenses" ADD COLUMN "importSource" "ImportSource" NOT NULL DEFAULT 'MANUAL';
ALTER TABLE "invoices" ADD COLUMN "lpoReference" TEXT;
ALTER TABLE "invoices" ADD COLUMN "lpoDocumentUrl" TEXT;
ALTER TABLE "invoices" ADD COLUMN "sourceQuotationRef" TEXT;
CREATE UNIQUE INDEX "expenses_supplierId_invoiceNumber_key" ON "expenses"("supplierId","invoiceNumber");
CREATE INDEX "expenses_importSource_status_idx" ON "expenses"("importSource","status");
