'use client';
import React, { useState } from 'react';
import { M_CSS, TAB5 } from './deviceCss';
import type { SxLadder, SxSpine, SxDirection, SxEpisode } from './ScripOnStudio';
import { useLocale } from '@/lib/i18n';
const SC = `.dvm .ladder{display:flex;flex-direction:column}.dvm .lstep{display:flex;gap:11px;padding:8px 0;position:relative}.dvm .lstep:before{content:"";position:absolute;left:11px;top:28px;bottom:-2px;width:2px;background:var(--hair)}.dvm .lstep:last-child:before{display:none}.dvm .lnum{width:24px;height:24px;border-radius:50%;flex:none;display:grid;place-items:center;font-size:11px;font-weight:800;z-index:1}.dvm .lstep.done .lnum{background:rgba(87,179,104,.18);color:var(--green)}.dvm .lstep.on .lnum{background:linear-gradient(160deg,var(--gold2),var(--gold));color:var(--goldink)}.dvm .lstep.wait .lnum{background:#1b1e25;color:var(--faint);border:1px solid var(--hair)}.dvm .ltt{font-size:12.5px;font-weight:700;color:var(--cream)}.dvm .lss{font-size:11px;color:var(--faint);margin-top:2px}.dvm .lstep.on .lbody{margin-top:7px;background:var(--paper);color:var(--ink);border-radius:8px;padding:10px 12px;font-size:11.5px;line-height:1.5}.dvm .kv{display:flex;justify-content:space-between;font-size:12px;padding:6px 0;border-top:1px solid var(--hair)}.dvm .kv:first-of-type{border-top:none}.dvm .kv .k{color:var(--faint)}.dvm .kv .v{color:var(--text);font-weight:600}.dvm .ta{width:100%;min-height:120px;background:#101218;border:1px solid var(--hair);border-radius:12px;padding:12px 13px;color:var(--text);font:inherit;font-size:12.5px;line-height:1.6;resize:vertical;outline:none}.dvm .dl{font-size:11px;font-weight:800;color:var(--gold2)}.dvm .dlog{font-size:12.5px;color:var(--cream);font-weight:600;line-height:1.4;margin:5px 0}.dvm .drow{font-size:11px;color:var(--mute);line-height:1.45}.dvm .drow b{color:var(--text)}.dvm .ep{display:flex;gap:11px;padding:4px 0}.dvm .epn{width:26px;height:26px;border-radius:8px;background:rgba(198,164,99,.14);color:var(--gold2);display:grid;place-items:center;font-weight:800;font-size:11px;flex:none}.dvm .ept{font-size:12.5px;font-weight:700;color:var(--cream)}.dvm .eprow{font-size:11px;color:var(--mute);line-height:1.45}.dvm .eprow b{color:var(--gold2)}.dvm .run{height:46px;border-radius:13px;background:linear-gradient(180deg,var(--gold2),var(--gold));color:var(--goldink);font-weight:700;font-size:14px;display:flex;align-items:center;justify-content:center;gap:7px;border:none;cursor:pointer}`;
const FORMATS = [['series', 'Series'], ['vertical', 'Vertical'], ['short', 'Short'], ['feature', 'Feature']];
type P = { title: string; meta: string; mode: string; onTab: (k: string) => void; ladder: SxLadder[]; spine: SxSpine[]; comps: string[]; adaptResult: SxDirection[]; formatResult: SxEpisode[]; formatTarget: string; busy?: string; onNav: (k: string) => void; onBack: () => void; onAction: (k: string) => void; onAdapt: (s: string) => void; onFormat: (t: string) => void; toast?: string | null };
export default function ScripOnStudioMobile(p: P) {
  const { dir, t } = useLocale();
  const [src, setSrc] = useState(''); const m = p.mode;
  return (<div className="dvm" dir={dir}><style dangerouslySetInnerHTML={{ __html: M_CSS + SC }} />
    <div className="sb"><span>9:41</span><div className="r"><svg viewBox="0 0 24 24"><path d="M2 20h.01M6 20v-4M10 20v-8M14 20V8M18 20V4" /></svg><svg viewBox="0 0 24 24"><rect x="2" y="7" width="18" height="10" rx="2" /></svg></div></div>
    <div className="mtop"><button className="dr" onClick={p.onBack}>TFM</button><div className="ti"><div className="t1">{t('Studio')}</div><div className="t2">{p.meta}</div></div></div>
    <div className="scroll"><div className="chips"><button className={'chip' + (m === 'builds' ? ' on' : '')} onClick={() => p.onTab('builds')}>{t('Builds')}</button><button className={'chip' + (m === 'develop' ? ' on' : '')} onClick={() => p.onTab('develop')}>{t('Develop')}</button></div>
      {m === 'develop' && <>
        <div className="card"><div className="pc-h"><span className="t">{t('The ladder')}</span><span className="eyebrow">{p.ladder.filter(s => s.state === 'done').length + 1} {t('OF')} {p.ladder.length}</span></div><div className="ladder">{p.ladder.map((s, i) => <div className={'lstep ' + s.state} key={i}><div className="lnum">{s.state === 'done' ? '✓' : i + 1}</div><div><div className="ltt">{s.name}</div>{s.state === 'on' && s.body ? <div className="lbody" dangerouslySetInnerHTML={{ __html: s.body }} /> : (s.sub && <div className="lss">{s.sub}</div>)}</div></div>)}</div></div>
        <div className="card"><div className="pc-h"><span className="t">{t('The spine')}</span><span className="eyebrow">{t('AGREED FIRST')}</span></div>{p.spine.map((s, i) => <div className="kv" key={i}><span className="k">{s.k}</span><span className="v">{s.v}</span></div>)}</div>
        <button className="run" onClick={() => p.onAction('advance')}>{t('Advance ladder')}</button></>}
      {m === 'adapt' && <>
        <div className="card"><div className="pc-h"><span className="t">{t('Source work')}</span><span className="eyebrow">{t('BOOK · STORY')}</span></div><textarea className="ta" placeholder={t('Paste a synopsis or excerpt…')} value={src} onChange={(e) => setSrc(e.target.value)} /></div>
        {p.adaptResult.map((d, i) => <div className="card" key={i}><div className="dl">{d.label}</div><div className="dlog">{d.logline}</div>{d.change && <div className="drow"><b>{t('Change:')}</b> {d.change}</div>}{d.risk && <div className="drow"><b>{t('Risk:')}</b> {d.risk}</div>}</div>)}
        <button className="run" onClick={() => p.onAdapt(src)}>{p.busy === 'adapt' ? t('Reading…') : t('Get directions')}</button></>}
      {m === 'format' && <>
        <div className="card"><div className="pc-h"><span className="t">{t('Convert to')}</span><span className="eyebrow">{t('KEEP THE ENGINE')}</span></div><div className="chips">{FORMATS.map(([k, l]) => <span key={k} className={'chip' + (p.formatTarget === k ? ' on' : '')} onClick={() => p.onAction('fmt-' + k)}>{t(l)}</span>)}</div></div>
        {p.formatResult.map((e, i) => <div className="card" key={i}><div className="ep"><div className="epn">{e.ep ?? i + 1}</div><div>{e.hook !== undefined ? <><div className="ept">{t('Episode')} {e.ep ?? i + 1}</div><div className="eprow"><b>{t('Hook:')}</b> {e.hook}</div>{e.cliffhanger && <div className="eprow"><b>{t('Cliff:')}</b> {e.cliffhanger}</div>}</> : <><div className="ept">{e.title || (t('Episode') + ' ' + (e.ep ?? i + 1))}</div>{e.engine && <div className="eprow"><b>{t('Engine:')}</b> {e.engine}</div>}</>}</div></div></div>)}
        <button className="run" onClick={() => p.onFormat(p.formatTarget)}>{p.busy === 'format' ? t('Converting…') : t('Convert')}</button></>}
    </div>
    <div className="tabbar">{TAB5.map(([k, l, d]) => <button key={k} className={'tab' + (k === 'studio' ? ' on' : '')} onClick={() => p.onNav(k)}><div className="b"><svg className="ico" viewBox="0 0 24 24"><path d={d} /></svg></div>{t(l)}</button>)}</div>
    {p.toast && <div className="toast">{p.toast}</div>}</div>);
}
