'use client';
import React, { useState } from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxLadder, SxSpine, SxDirection, SxEpisode } from './ScripOnStudio';
import { useLocale } from '@/lib/i18n';
const SC = `.dvt .modes{display:flex;gap:7px}.dvt .sgrid{flex:1;display:grid;grid-template-columns:1.5fr 1fr;gap:13px;min-height:0}.dvt .ladder{background:var(--panel);border:1px solid var(--hair);border-radius:14px;padding:13px 15px;overflow:auto;display:flex;flex-direction:column}.dvt .lstep{display:flex;gap:11px;padding:10px 0;position:relative}.dvt .lstep:before{content:"";position:absolute;left:11px;top:30px;bottom:-2px;width:2px;background:var(--hair)}.dvt .lstep:last-child:before{display:none}.dvt .lnum{width:24px;height:24px;border-radius:50%;flex:none;display:grid;place-items:center;font-size:11px;font-weight:800;z-index:1}.dvt .lstep.done .lnum{background:rgba(87,179,104,.18);color:var(--green)}.dvt .lstep.on .lnum{background:linear-gradient(160deg,var(--gold2),var(--gold));color:var(--goldink)}.dvt .lstep.wait .lnum{background:#1b1e25;color:var(--faint);border:1px solid var(--hair)}.dvt .ltt{font-size:12.5px;font-weight:700;color:var(--cream)}.dvt .lss{font-size:11px;color:var(--faint);margin-top:2px}.dvt .lstep.on .lbody{margin-top:8px;background:var(--paper);color:var(--ink);border-radius:8px;padding:11px 13px;font-size:11.5px;line-height:1.55}.dvt .col{display:flex;flex-direction:column;gap:13px;min-height:0}.dvt .kv{display:flex;justify-content:space-between;font-size:12px;padding:6px 0;border-top:1px solid var(--hair)}.dvt .kv:first-child{border-top:none}.dvt .kv .k{color:var(--faint)}.dvt .kv .v{color:var(--text);font-weight:600}.dvt .scrl{flex:1;overflow:auto;display:flex;flex-direction:column;gap:13px}.dvt .ta{width:100%;min-height:120px;background:#101218;border:1px solid var(--hair);border-radius:12px;padding:12px 14px;color:var(--text);font:inherit;font-size:12.5px;line-height:1.6;resize:vertical;outline:none}.dvt .dirs{display:grid;grid-template-columns:1fr 1fr;gap:12px}.dvt .dir{background:var(--panel);border:1px solid var(--hair);border-radius:13px;padding:14px;display:flex;flex-direction:column;gap:7px}.dvt .dl{font-size:11px;font-weight:800;color:var(--gold2)}.dvt .dlog{font-size:12.5px;color:var(--cream);font-weight:600;line-height:1.4}.dvt .drow{font-size:11px;color:var(--mute);line-height:1.45}.dvt .drow b{color:var(--text)}.dvt .eps{display:flex;flex-direction:column;gap:9px}.dvt .ep{background:var(--panel);border:1px solid var(--hair);border-radius:12px;padding:12px 13px;display:flex;gap:11px}.dvt .epn{width:28px;height:28px;border-radius:8px;background:rgba(198,164,99,.14);color:var(--gold2);display:grid;place-items:center;font-weight:800;font-size:11px;flex:none}.dvt .ept{font-size:12.5px;font-weight:700;color:var(--cream)}.dvt .eprow{font-size:11px;color:var(--mute);line-height:1.45}.dvt .eprow b{color:var(--gold2)}`;
const FORMATS = [['series', 'Series'], ['vertical', 'Vertical'], ['short', 'Short'], ['feature', 'Feature']];
type P = { title: string; meta: string; mode: string; onTab: (k: string) => void; ladder: SxLadder[]; spine: SxSpine[]; comps: string[]; adaptResult: SxDirection[]; formatResult: SxEpisode[]; formatTarget: string; busy?: string; onNav: (k: string) => void; onBack: () => void; onAction: (k: string) => void; onAdapt: (s: string) => void; onFormat: (t: string) => void; toast?: string | null; osNew?: boolean };
export default function ScripOnStudioTablet(p: P) {
  const { dir, t } = useLocale();
  const [src, setSrc] = useState(''); const m = p.mode;
  return (<div className={'dvt' + (p.osNew ? ' osnew' : '')} dir={dir}><style dangerouslySetInnerHTML={{ __html: T_CSS + SC + '.dvt.osnew .h1{font-family:var(--sx-title);font-weight:500;letter-spacing:-.3px}' }} />
    <div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{t('Studio')}</div></div>
      <div className="seg">{SEG5.map(([k, l, d]) => <button key={k} className={'segtab' + (k === 'studio' ? ' on' : '')} onClick={() => p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d} /></svg>{t(l)}</button>)}</div>
      {m === 'develop' && <button className="btn gold" onClick={() => p.onAction('advance')}>{t('Advance')}</button>}
      {m === 'adapt' && <button className="btn gold" onClick={() => p.onAdapt(src)}>{p.busy === 'adapt' ? t('Reading…') : t('Get directions')}</button>}
      {m === 'format' && <button className="btn gold" onClick={() => p.onFormat(p.formatTarget)}>{p.busy === 'format' ? t('Converting…') : t('Convert')}</button>}</div>
    <div className="content"><div><div className="h1">{m === 'adapt' ? t('Adapt → script') : m === 'format' ? t('Convert format') : t('Develop → script')}</div><div className="sub">{t('Nothing is written until the spine is agreed.')}</div></div>
      <div className="modes"><button className={'chip' + (m === 'builds' ? ' on' : '')} onClick={() => p.onTab('builds')}>{t('Builds')}</button><button className={'chip' + (m === 'develop' ? ' on' : '')} onClick={() => p.onTab('develop')}>{t('Develop')}</button></div>
      {m === 'develop' && <div className="sgrid"><div className="ladder">{p.ladder.map((s, i) => <div className={'lstep ' + s.state} key={i}><div className="lnum">{s.state === 'done' ? '✓' : i + 1}</div><div><div className="ltt">{s.name}</div>{s.sub && <div className="lss">{s.sub}</div>}{s.state === 'on' && s.body && <div className="lbody" dangerouslySetInnerHTML={{ __html: s.body }} />}</div></div>)}</div>
        <div className="col"><div className="card"><div className="pc-h"><span className="t">{t('The spine')}</span><span className="eyebrow">{t('AGREED FIRST')}</span></div>{p.spine.map((s, i) => <div className="kv" key={i}><span className="k">{s.k}</span><span className="v">{s.v}</span></div>)}</div>
          <div className="card" style={{ flex: 1 }}><div className="pc-h"><span className="t">{t('Comparables')}</span><span className="eyebrow">{t('AUTO')}</span></div><div className="chips">{p.comps.map((c, i) => <span className="chip on" key={i}>{c}</span>)}</div></div></div></div>}
      {m === 'adapt' && <div className="scrl"><div className="card"><div className="pc-h"><span className="t">{t('Source work')}</span><span className="eyebrow">{t('BOOK · STORY')}</span></div><textarea className="ta" placeholder={t('Paste a synopsis or excerpt of the source work…')} value={src} onChange={(e) => setSrc(e.target.value)} /></div>
        {p.adaptResult.length > 0 && <div className="dirs">{p.adaptResult.map((d, i) => <div className="dir" key={i}><div className="dl">{d.label}</div><div className="dlog">{d.logline}</div>{d.change && <div className="drow"><b>{t('Change:')}</b> {d.change}</div>}{d.risk && <div className="drow"><b>{t('Risk:')}</b> {d.risk}</div>}</div>)}</div>}</div>}
      {m === 'format' && <div className="scrl"><div className="card"><div className="pc-h"><span className="t">{t('Convert to')}</span><span className="eyebrow">{t('KEEP THE ENGINE')}</span></div><div className="chips">{FORMATS.map(([k, l]) => <span key={k} className={'chip' + (p.formatTarget === k ? ' on' : '')} onClick={() => p.onAction('fmt-' + k)}>{t(l)}</span>)}</div></div>
        {p.formatResult.length > 0 && <div className="eps">{p.formatResult.map((e, i) => <div className="ep" key={i}><div className="epn">{e.ep ?? i + 1}</div><div>{e.hook !== undefined ? <><div className="ept">{t('Episode')} {e.ep ?? i + 1}</div><div className="eprow"><b>{t('Hook:')}</b> {e.hook}</div>{e.cliffhanger && <div className="eprow"><b>{t('Cliff:')}</b> {e.cliffhanger}</div>}</> : <><div className="ept">{e.title || (t('Episode') + ' ' + (e.ep ?? i + 1))}</div>{e.engine && <div className="eprow"><b>{t('Engine:')}</b> {e.engine}</div>}</>}</div></div>)}</div>}</div>}
    </div>{p.toast && <div className="toast">{p.toast}</div>}</div>);
}
