'use client';
import React from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxReport, SxPreview } from './ScripOnReports';
import { useLocale } from '@/lib/i18n';
const SC=`.dvt .rg{flex:1;display:grid;grid-template-columns:1.5fr 1fr;gap:14px;min-height:0}.dvt .rl{display:grid;grid-template-columns:1fr 1fr;gap:11px;align-content:start;overflow:auto}.dvt .rc{background:var(--panel);border:1px solid var(--hair);border-radius:12px;padding:13px;display:flex;align-items:center;gap:11px;cursor:pointer}.dvt .rc.on{border-color:rgba(198,164,99,.5);background:#181a16}.dvt .ri{width:40px;height:40px;border-radius:10px;background:rgba(198,164,99,.13);display:grid;place-items:center;color:var(--gold2);flex:none}.dvt .rt{font-size:13px;font-weight:700;color:var(--cream)}.dvt .rm{font-size:10.5px;color:var(--faint);margin-top:2px}.dvt .ppr{background:var(--paper);color:var(--ink);border-radius:8px;padding:16px;font-family:'Courier Prime',monospace;font-size:11px;line-height:1.7}.dvt .ph{display:flex;justify-content:space-between;border-bottom:1.5px solid #cdc6b2;padding-bottom:7px;margin-bottom:8px;font-weight:700}.dvt .pl{margin-top:5px}.dvt .pl b{background:#efe7cf}`;
type P={title:string;meta:string;filters:string[];activeFilter:string;onFilter:(f:string)=>void;reports:SxReport[];activeKey?:string;onSelect:(k:string)=>void;preview:SxPreview;onExport:(f:string)=>void;onAction:(k:string)=>void;onNav:(k:string)=>void;onBack:()=>void;toast?:string|null};
export default function ScripOnReportsTablet(p:P){const{dir,t}=useLocale();return(<div className="dvt" dir={dir}><style dangerouslySetInnerHTML={{__html:T_CSS+SC}}/>
<div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{t('Reports & Exports')}</div></div><div className="seg">{SEG5.map(([k,l,d])=><button key={k} className="segtab" onClick={()=>p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d}/></svg>{t(l)}</button>)}</div><button className="btn gold" onClick={()=>p.onExport('all')}><svg className="ico" viewBox="0 0 24 24" style={{stroke:'#1a1509'}}><path d="M12 3v12M7 10l5 5 5-5M5 21h14"/></svg>{t('Export all')}</button></div>
<div className="content"><div className="chips">{p.filters.map(f=><button key={f} className={'chip'+(f===p.activeFilter?' on':'')} onClick={()=>p.onFilter(f)}>{f}</button>)}</div>
<div className="rg"><div className="rl">{p.reports.map(r=><button key={r.key} className={'rc'+(r.key===p.activeKey?' on':'')} onClick={()=>p.onSelect(r.key)}><div className="ri"><svg className="ico" viewBox="0 0 24 24" style={{width:20,height:20}}><path d="M6 2h9l5 5v15H6z"/></svg></div><div style={{flex:1}}><div className="rt">{r.title}</div><div className="rm">{r.meta}</div></div><span className={'badge '+r.badgeClass}>{r.badge}</span></button>)}</div>
<div style={{display:'flex',flexDirection:'column',gap:12}}><div className="ppr"><div className="ph"><span>{p.preview.title}</span><span>{p.preview.badge}</span></div>{p.preview.lines.map((l,i)=><div className="pl" key={i}>{l.label&&<b>{l.label} </b>}{l.text}</div>)}</div><div className="card"><div className="pc-h"><span className="t">{t('Export')}</span></div><div className="qa"><button className="tile" onClick={()=>p.onExport('pdf')}><div className="ti"><svg className="ico" viewBox="0 0 24 24"><path d="M6 2h9l5 5v15H6z"/></svg></div><div className="tt">{t('PDF')}</div></button><button className="tile" onClick={()=>p.onExport('xlsx')}><div className="ti"><svg className="ico" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="2"/></svg></div><div className="tt">{t('Excel')}</div></button></div></div></div></div></div>
{p.toast&&<div className="toast">{p.toast}</div>}</div>);}
