'use client';
import React from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxKCol, SxStep } from './ScripOnApprovals';
import { useLocale } from '@/lib/i18n';
const SC=`.dvt .ap{flex:1;display:grid;grid-template-columns:1fr 300px;gap:14px;min-height:0}.dvt .kan{display:flex;gap:10px;overflow:auto}.dvt .kc{min-width:172px;flex:1;background:var(--panel);border:1px solid var(--hair);border-radius:12px;display:flex;flex-direction:column}.dvt .kh{padding:10px 12px;border-bottom:1px solid var(--hair);display:flex;justify-content:space-between;font-size:11.5px;font-weight:700;color:var(--cream)}.dvt .cd{width:8px;height:8px;border-radius:50%;display:inline-block;margin-inline-end:6px}.dvt .kb{padding:8px;display:flex;flex-direction:column;gap:7px}.dvt .kcard{background:linear-gradient(180deg,#1b1e25,#171a20);border:1px solid var(--hair);border-radius:10px;padding:10px}.dvt .kct{font-size:12px;font-weight:700;color:var(--cream)}.dvt .kcm{font-size:10px;color:var(--faint);margin-top:3px}.dvt .chain{background:var(--panel);border:1px solid var(--hair);border-radius:14px;padding:15px;display:flex;flex-direction:column;gap:10px}.dvt .crow{display:flex;align-items:center;gap:10px;padding:9px 0;border-top:1px solid var(--hair)}.dvt .crow:first-of-type{border-top:none}.dvt .cst{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;flex:none}.dvt .cnn{font-size:12px;font-weight:600;color:var(--cream)}.dvt .cnr{font-size:10px;color:var(--faint)}.dvt .gate{background:rgba(198,164,99,.07);border:1px solid rgba(198,164,99,.25);border-radius:11px;padding:11px}.dvt .kv{display:flex;justify-content:space-between;font-size:12px;padding:4px 0}.dvt .kv .k{color:var(--faint)}.dvt .kv .v{color:var(--text);font-weight:600}`;
const ST:any={done:{bg:'rgba(87,179,104,.18)',c:'var(--green)',d:'M20 6L9 17l-5-5'},current:{bg:'rgba(91,141,239,.18)',c:'var(--blue)',d:'M12 7v5l3 2'},pending:{bg:'#1b1e25',c:'var(--faint)',d:''}};
type P={title:string;meta:string;columns:SxKCol[];chainRev:string;chainColor:string;steps:SxStep[];lockLabel:string;onAction:(k:string)=>void;onNav:(k:string)=>void;onBack:()=>void;toast?:string|null};
export default function ScripOnApprovalsTablet(p:P){const{dir,t}=useLocale();return(<div className="dvt" dir={dir}><style dangerouslySetInnerHTML={{__html:T_CSS+SC}}/>
<div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{t('Approvals & Sign-off')}</div></div><div className="seg">{SEG5.map(([k,l,d])=><button key={k} className="segtab" onClick={()=>p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d}/></svg>{t(l)}</button>)}</div><button className="btn gold" onClick={()=>p.onAction('new')}><svg className="ico" viewBox="0 0 24 24" style={{stroke:'#1a1509'}}><path d="M12 5v14M5 12h14"/></svg>{t('New routing')}</button></div>
<div className="content"><div className="ap"><div className="kan">{p.columns.map((col,i)=><div className="kc" key={i}><div className="kh"><span><span className="cd" style={{background:col.color}}/>{t(col.label)}</span><span>{col.count}</span></div><div className="kb">{col.cards.map((c,j)=><div className="kcard" key={j} style={c.selected?{borderColor:'rgba(198,164,99,.5)',background:'#181a16'}:undefined}><div className="kct">{c.title}</div><div className="kcm">{c.sub}</div></div>)}</div></div>)}</div>
<div className="chain"><div className="pc-h"><span className="t">{t('Approval chain')}</span><span className="pill" style={{background:p.chainColor+'28',color:p.chainColor}}><span className="d" style={{background:p.chainColor}}/>{p.chainRev.toUpperCase()}</span></div>{p.steps.map((s,i)=><React.Fragment key={i}>{i===3&&<div className="gate"><div className="eyebrow" style={{marginBottom:7}}>{t('COMPLIANCE GATE')}</div><div className="kv"><span className="k">{t('Rating')}</span><span className="v" style={{color:'var(--gold2)'}}>PG-15</span></div><div className="kv" style={{borderTop:'1px solid var(--hair)'}}><span className="k">{t('Culture')}</span><span className="badge amber">{t('1 FLAG')}</span></div><div className="kv" style={{cursor:'pointer'}} onClick={()=>p.onAction('compliance')}><span className="k" style={{color:'var(--gold2)'}}>{t('Run screen')} {dir==='rtl'?'←':'→'}</span></div></div>}<div className="crow"><span className="cst" style={{background:ST[s.state].bg,color:ST[s.state].c}}>{ST[s.state].d?<svg className="ico" viewBox="0 0 24 24" style={{width:13,height:13}}><path d={ST[s.state].d}/></svg>:<svg className="ico" viewBox="0 0 24 24" style={{width:13,height:13}}><circle cx="12" cy="12" r="9"/></svg>}</span><div><div className="cnn">{s.name}</div><div className="cnr">{s.role}</div></div></div></React.Fragment>)}</div></div></div>
{p.toast&&<div className="toast">{p.toast}</div>}</div>);}
