'use client';
import React from 'react';
import { T_CSS, SEG5 } from './deviceCss';
import type { SxDay, SxBudRow, SxKpi } from './ScripOnSchedule';
import { useLocale } from '@/lib/i18n';
const SC = `.dvt .kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:11px}.dvt .kpi{background:linear-gradient(180deg,#16191f,#131519);border:1px solid var(--hair);border-radius:12px;padding:13px}.dvt .kl{font-size:10px;color:var(--faint);font-weight:600}.dvt .kv{font-size:20px;font-weight:800;color:var(--cream);margin-top:5px}.dvt .kc{font-size:10px;margin-top:4px;font-weight:600}.dvt .board{flex:1;display:flex;gap:11px;min-height:0;overflow:auto}.dvt .day{min-width:210px;flex:1;background:var(--panel);border:1px solid var(--hair);border-radius:12px;display:flex;flex-direction:column}.dvt .dayh{padding:9px 11px;border-bottom:1px solid var(--hair);display:flex;justify-content:space-between;align-items:center}.dvt .dn{font-size:12px;font-weight:700;color:var(--cream)}.dvt .dm{font-size:10px;color:var(--faint)}.dvt .daybody{padding:8px;display:flex;flex-direction:column;gap:6px;overflow:auto}.dvt .strip{border-radius:7px;padding:7px 9px;display:grid;grid-template-columns:22px 1fr;gap:6px}.dvt .sn{font-weight:800;font-size:11px;align-self:center}.dvt .ss{font-size:11px;font-weight:700;line-height:1.2}.dvt .sc{font-size:9px;opacity:.7;grid-column:2}.dvt .budget{display:flex;gap:14px;flex-wrap:wrap}.dvt .brow{flex:1;min-width:150px}.dvt .bt{display:flex;justify-content:space-between;font-size:12px;margin-bottom:5px}.dvt .bbar{height:6px;border-radius:4px;background:#23262e;overflow:hidden}.dvt .bbar i{display:block;height:100%}`;
type P = { title: string; meta: string; kpis: SxKpi[]; days: SxDay[]; budget: SxBudRow[]; suggestion: any; onAction: (k: string) => void; onNav: (k: string) => void; onBack: () => void; toast?: string | null };
export default function ScripOnScheduleTablet(p: P) {
  const { dir, t } = useLocale();
  return (<div className="dvt" dir={dir}><style dangerouslySetInnerHTML={{ __html: T_CSS + SC }} />
    <div className="top"><div className="tl"><div className="logo" onClick={p.onBack}>TFM</div><div className="proj">{t('Schedule & Budget')}</div></div>
      <div className="seg">{SEG5.map(([k, l, d]) => <button key={k} className={'segtab' + (k === 'schedule' ? ' on' : '')} onClick={() => k !== 'schedule' && p.onNav(k)}><svg className="ico" viewBox="0 0 24 24"><path d={d} /></svg>{t(l)}</button>)}</div>
      <button className="btn gold" onClick={() => p.onAction('optimise')}><svg className="ico" viewBox="0 0 24 24" style={{ stroke: '#1a1509' }}><path d="M12 2l9 5-9 5-9-5z" /></svg>{t('Optimise')}</button></div>
    <div className="content"><div><div className="h1">{t('Schedule & Budget')}</div><div className="sub">{p.meta}</div></div>
      <div className="kpis">{p.kpis.map((k, i) => <div className="kpi" key={i}><div className="kl">{t(k.label, k.label)}</div><div className="kv" style={{ color: k.tone || 'var(--cream)' }}>{k.value}</div><div className="kc" style={{ color: k.tone || 'var(--mute)' }}>{t(k.caption || '', k.caption || '')}</div></div>)}</div>
      {p.days.length ? <div className="board">{p.days.map((d, i) => <div className="day" key={i}><div className="dayh"><div><div className="dn">{d.label}</div><div className="dm">{d.sub}</div></div><span className={'badge ' + d.ppTone}>{d.pp}</span></div><div className="daybody">{d.strips.map((s, j) => <div className="strip" key={j} style={{ background: s.bg, color: s.fg }}><span className="sn">{s.num}</span><span className="ss">{s.slug}</span><span className="sc">{s.cast}</span></div>)}</div></div>)}</div> : <div className="card"><div className="sub">{t('No strips scheduled yet.')}</div></div>}
      <div className="card"><div className="pc-h"><span className="t">{t('Budget by category')}</span><span className="eyebrow">{t('EFC')}</span></div><div className="budget">{p.budget.map((b, i) => <div className="brow" key={i}><div className="bt"><span>{t(b.name, b.name)}</span><span style={{ color: 'var(--mute)' }}>{b.val}</span></div><div className="bbar"><i style={{ width: b.pct + '%', background: b.tone }} /></div></div>)}</div></div>
    </div>
    {p.toast && <div className="toast">{p.toast}</div>}
  </div>);
}
