import { yearsToDays } from './era.util';
import { roundHalfAwayFromZero } from './era-days.util';

/**
 * ERA -> YEAR — what year a named period means, and when to refuse to say.
 *
 * `settingEra` can derive the build's present year only if the chosen period HAS a year. This file
 * is that map, and the standing rule applies: a constant that cannot say where it came from is a
 * constant nobody can audit, so every row carries the clause that fixes its boundary.
 *
 * TWO THINGS THIS FILE DELIBERATELY WILL NOT DO.
 *
 *   1. IT WILL NOT ANCHOR AN UNSOUND LABEL. 39 of the 279 rows name more than one polity, or name
 *      something whose identification is not established. "Ibadi Imamate" is eight discontinuous
 *      imamates over 1,200 years, and its midpoint — 1355 — falls inside the Nabhani gap, a year in
 *      which no imamate existed. Such a row returns NO year and a reason. Offsets are relative, so
 *      everything else still works; only the printed year waits for the user.
 *   2. IT WILL NOT BE READ BACKWARDS. The era list is a creative MENU of evocative periods, not a
 *      calendar: it has 35 gaps of more than 25 years (57 of any size, and 2,430 unlabelled years between the UAE's
 *      Bronze Age and its Islamic era) and 34 overlaps. So era -> year only. A year -> era lookup would be undefined
 *      across the gaps and ambiguous across the overlaps, and nothing in the design needs one.
 *      The overlaps are mostly the occupying-power rows, which NEST inside the civilisational ones on
 *      purpose: 1600 in Bahrain is both 'Islamic Bahrain' and 'Portuguese Bahrain', and which one a
 *      script means is a creative choice the writer makes, not one this file can compute.
 *
 * The keys are the exact option labels the form shows. A renamed label simply misses, and a miss is
 * a SUPPORTED STATE — the anchor falls through to the generic band and then to the current year.
 *
 * PURE. NEVER THROWS.
 */

/** '' = uncontroversial · 'disputed' = a boundary scholars move by more than ~50 years ·
 *  'unsound' = the LABEL will not carry an anchor at all. */
export type EraFlag = '' | 'disputed' | 'unsound';

export interface EraRow {
  country: string;
  /** The exact label string the form displays. */
  label: string;
  /** null where no start is sourced at all - the row is a period nobody dated the beginning of. */
  start: number | null;
  /** null means "the story's own present" — so a modern-era anchor never goes stale. */
  end: number | null;
  flag: EraFlag;
  basis: string;
  /**
   * A standing disclosure the row ALWAYS carries, whatever its flag says about dates. Empty on
   * almost every row. It is appended to EVERY verdict for the row - clean, disputed or refused -
   * because it states a fact about the place, not a confidence about a boundary, and those are
   * different axes. A writer who picks any present-day Palestinian era must be told the land is
   * occupied whether or not the dates of that era are in doubt.
   */
  standing?: string;
}

/** The nine generic bands, for a country with no deep timeline. Six state their own range in the
 *  label the user already reads, so those rows record what the UI has always claimed. */
export interface BandRow { id: string; start: number | null; end: number | null; offset?: number }
export const ERA_BANDS: BandRow[] = [
  { id: 'ancient', start: -3000, end: 500 },
  { id: 'medieval', start: 500, end: 1500 },
  { id: 'early-modern', start: 1500, end: 1800 },
  { id: '19c', start: 1800, end: 1900 },
  { id: 'early-20c', start: 1900, end: 1940 },
  { id: 'mid-20c', start: 1940, end: 1979 },
  { id: 'contemporary', start: null, end: null, offset: 0 },
  { id: 'near-future', start: null, end: null, offset: 25 },
  { id: 'far-future', start: null, end: null, offset: 150 },
];

export const COUNTRY_ERA_YEARS: EraRow[] = [
  { country: 'Egypt', label: 'Pharaonic', start: -3099, end: -331, flag: 'disputed', basis: 'Unification / 1st Dynasty to Alexander\'s conquest' },
  { country: 'Egypt', label: 'Ptolemaic / Greco-Roman', start: -331, end: 641, flag: 'unsound', basis: 'Alexander through Ptolemaic and Roman/Byzantine rule to the Arab conquest' },
  { country: 'Egypt', label: 'Coptic', start: 300, end: 641, flag: 'disputed', basis: 'Christianisation of Egypt to the Arab conquest' },
  { country: 'Egypt', label: 'Arab-Islamic', start: 641, end: 1517, flag: '', basis: 'Arab conquest 639–642 to Selim I\'s conquest 1517' },
  { country: 'Egypt', label: 'Ottoman', start: 1517, end: 1798, flag: 'disputed', basis: 'Ottoman conquest to Napoleon\'s invasion' },
  { country: 'Egypt', label: 'British occupation', start: 1882, end: 1922, flag: 'disputed', basis: 'Occupation after Tel el-Kebir, Sept 1882, through the 1914 protectorate to the unilateral declaration of independence, 28 Feb 1922; British troops remain until 1956' },
  { country: 'Egypt', label: 'Modern Egyptian', start: 1805, end: null, flag: '', basis: 'Accession of Muhammad Ali' },
  { country: 'Iraq', label: 'Sumer / Akkad / Babylon', start: -3999, end: -538, flag: 'unsound', basis: 'Uruk-period Sumer to Cyrus\'s capture of Babylon' },
  { country: 'Iraq', label: 'Abbasid Baghdad', start: 762, end: 1258, flag: '', basis: 'al-Manṣūr founds Baghdad to Hülegü\'s sack' },
  { country: 'Iraq', label: 'Ottoman Iraq', start: 1534, end: 1917, flag: 'disputed', basis: 'Süleyman I takes Baghdad 1534 to the British occupation of Baghdad, March 1917; the Safavids hold Baghdad 1623-1638' },
  { country: 'Iraq', label: 'British Mandate', start: 1920, end: 1932, flag: '', basis: 'San Remo assigns the mandate, April 1920, to Iraq\'s admission to the League of Nations, 3 Oct 1932' },
  { country: 'Iraq', label: 'Modern Iraq', start: 1920, end: null, flag: '', basis: 'British Mandate / creation of the Iraqi state' },
  { country: 'Iraq', label: 'Achaemenid Babylonia', start: -538, end: -330, flag: '', basis: 'Cyrus the Great\'s army takes Babylon without a fight, 12 Oct 539 BC, ending Neo-Babylonian rule, to Alexander\'s entry into Babylon shortly after his victory at Gaugamela, 331 BC.' },
  { country: 'Iraq', label: 'Sasanian Mesopotamia', start: 224, end: 637, flag: '', basis: 'Ardashir I kills the last Parthian king at the Battle of Hormozdgan, 224, founding the Sasanian Empire, to the Arab capture of the Sasanian capital Ctesiphon in 637, following the Battle of al-Qadisiyyah, 636.' },
  { country: 'Iraq', label: 'Seleucid Mesopotamia', start: -330, end: -140, flag: 'disputed', basis: 'Alexander\'s entry into Babylon, 331 BC, opens Macedonian rule, but Seleucus I only secures Babylon for himself in 312 BC - the year that becomes the epoch of the Seleucid Era - a 19-year spread on when properly \'Seleucid\' rule begins; ends when the Parthian king Mithridates I captures Babylon, 141 BC.' },
  { country: 'Iraq', label: 'Parthian Mesopotamia', start: -140, end: 224, flag: '', basis: 'Mithridates I of Parthia captures Babylon in 141 BC, bringing Mesopotamia under Arsacid rule; ends when Ardashir I kills the last Parthian king, Artabanus IV, at the Battle of Hormozdgan, 224, founding the Sasanian Empire.' },
  { country: 'Iraq', label: 'Rashidun & Umayyad Iraq', start: 637, end: 750, flag: '', basis: 'Arab forces take the Sasanian capital Ctesiphon in 637, following the Battle of al-Qadisiyyah, 636, opening Rashidun and then Umayyad rule administered from the garrison cities of Kufa and Basra - where Ali is assassinated in 661 and Hussein is killed at Karbala in 680 - to the Abbasid revolution\'s victory at the Battle of the Zab, 25 January 750.' },
  { country: 'Greece', label: 'Classical', start: -479, end: -322, flag: '', basis: 'End of the Persian Wars to Alexander\'s death' },
  { country: 'Greece', label: 'Hellenistic / Koine', start: -322, end: -29, flag: 'disputed', basis: 'Alexander\'s death to Rome\'s conquest of Egypt' },
  { country: 'Greece', label: 'Modern Greece', start: 1821, end: null, flag: '', basis: 'War of Independence 1821, sovereignty 1830' },
  { country: 'Greece', label: 'Roman Greece', start: -145, end: 330, flag: 'disputed', basis: 'Roman victory at the Battle of Corinth, 146 BC, dissolves the Achaean League and brings Greece into the province of Macedonia, though Augustus does not organize Achaea as its own province until 27 BC, a 119-year spread on the start; ends when Constantine dedicates Constantinople as the new capital, 11 May 330.' },
  { country: 'Greece', label: 'Byzantine Greece', start: 330, end: 1204, flag: 'disputed', basis: 'Constantine\'s dedication of Constantinople, 11 May 330, though many historians instead date the Roman-Byzantine break to Theodosius\'s death and the empire\'s formal east-west split, 395, a 65-year spread on the start; ends with the Fourth Crusade\'s sack of Constantinople, 12 April 1204.' },
  { country: 'Greece', label: 'Frankokratia (Frankish & Venetian Greece)', start: 1204, end: 1669, flag: 'unsound', basis: 'The label spans a patchwork of separate Latin lordships with no common endpoint: the Duchy of Athens falls to the Ottomans in 1456, the Despotate of the Morea in 1460, while Venetian Crete holds out until 1669 and the Ionian Islands never fall to the Ottomans at all - so no single year represents the label.' },
  { country: 'Greece', label: 'Ottoman Greece', start: 1453, end: 1821, flag: 'disputed', basis: 'Fall of Constantinople, 29 May 1453, though Ottoman conquest of the mainland continues through the capture of Athens in 1458 and the Morea in 1460, and Venetian Crete resists until 1669 - a spread of over two centuries on the start; ends with the outbreak of the War of Independence, 25 March 1821.' },
  { country: 'Britain', label: 'Anglo-Saxon', start: 410, end: 1066, flag: '', basis: 'End of Roman Britain to the Norman Conquest' },
  { country: 'Britain', label: 'Norman / Medieval', start: 1066, end: 1485, flag: 'unsound', basis: 'Norman Conquest to Bosworth' },
  { country: 'Britain', label: 'Tudor / Early Modern', start: 1485, end: 1750, flag: 'unsound', basis: 'Accession of Henry VII to the conventional early-modern close' },
  { country: 'Britain', label: 'Modern Britain', start: 1750, end: null, flag: 'disputed', basis: 'Conventional early-modern / modern divide' },
  { country: 'Britain', label: 'Roman Britain', start: 43, end: 410, flag: '', basis: 'Claudius\'s invasion lands four legions in Kent, AD 43, beginning the province, to the conventional end of Roman rule, AD 410, when Emperor Honorius\'s rescript tells the British civitates to look to their own defence.' },
  { country: 'Mexico', label: 'Mesoamerican (Aztec/Maya)', start: -1799, end: 1521, flag: 'unsound', basis: 'Earliest Maya Preclassic to the fall of Tenochtitlán' },
  { country: 'Mexico', label: 'New Spain (Colonial)', start: 1521, end: 1821, flag: '', basis: 'Fall of Tenochtitlán to the Treaty of Córdoba' },
  { country: 'Mexico', label: 'Modern Mexico', start: 1821, end: null, flag: '', basis: 'Independence under the Treaty of Córdoba' },
  { country: 'Mexico', label: 'Second Mexican Empire (French Intervention)', start: 1862, end: 1867, flag: '', basis: 'French troops land at Veracruz, 7 Jan 1862, beginning the intervention that installs Maximilian\'s empire in 1864, to his execution at Querétaro, 19 June 1867.' },
  { country: 'Mexico', label: 'Mexican Revolution', start: 1910, end: 1920, flag: 'disputed', basis: 'Madero\'s Plan de San Luis Potosí calls for revolt against Díaz beginning 20 Nov 1910; the end is genuinely contested, with the armed phase often closed at Obregón\'s inauguration, 1 Dec 1920, though many historians extend the Revolution into the 1920s-40s.' },
  { country: 'Japan', label: 'Heian', start: 794, end: 1185, flag: '', basis: 'Capital moved to Heian-kyō to the fall of the Taira' },
  { country: 'Japan', label: 'Edo / Tokugawa', start: 1603, end: 1867, flag: '', basis: 'Ieyasu made shogun to the shogunate\'s surrender of power' },
  { country: 'Japan', label: 'Modern Japan', start: 1868, end: null, flag: '', basis: 'Meiji Restoration' },
  { country: 'Japan', label: 'Kamakura', start: 1185, end: 1333, flag: 'disputed', basis: 'Minamoto no Yoritomo\'s victory over the Taira at Dan-no-ura, 1185, establishes his military government, though the title of shogun is not granted until 1192, a real 7-year spread on the start; ends with the Hōjō regents\' fall and mass suicide at Kamakura, 1333.' },
  { country: 'Japan', label: 'Muromachi', start: 1336, end: 1573, flag: '', basis: 'Ashikaga Takauji issues the Kenmu Code establishing his bakufu in Kyoto, 1336, to Oda Nobunaga\'s expulsion of the last Ashikaga shogun, Yoshiaki, from Kyoto, 1573.' },
  { country: 'Japan', label: 'Sengoku', start: 1467, end: 1615, flag: 'disputed', basis: 'The Ōnin War opens the age of provincial warfare, 1467; the end is argued anywhere from Nobunaga\'s 1568 entry into Kyoto to Sekigahara in 1600 or the Tokugawa shogunate\'s founding in 1603, so this row uses the fall of Osaka Castle, 1615, which eliminates the Toyotomi for good.' },
  { country: 'Japan', label: 'Allied Occupation', start: 1945, end: 1952, flag: '', basis: 'Japan\'s surrender aboard USS Missouri, 2 Sept 1945, to the Treaty of San Francisco taking effect, 28 April 1952, ending Allied administration under SCAP.' },
  { country: 'Saudi Arabia', label: 'Pre-Islamic Arabia (Jāhiliyya)', start: null, end: 610, flag: 'unsound', basis: 'Ends at the first Qur\'anic revelation; jahiliyya is defined only relative to it and has no sourced start' },
  { country: 'Saudi Arabia', label: 'Early Islamic Hijaz', start: 610, end: 661, flag: 'disputed', basis: 'Revelation / Hijra to the end of Rashidun rule from Medina' },
  { country: 'Saudi Arabia', label: 'Ottoman Hejaz & al-Hasa', start: 1517, end: 1918, flag: 'unsound', basis: 'The label names the two COASTS only - Najd was never held. Selim I takes the Hejaz 1517 and holds it to the Arab Revolt of 1916 and the collapse of 1918; al-Hasa is held 1550-1670 and again 1871 until Ibn Saud takes it in 1913. Two coasts, three spans, so no single year represents the label' },
  { country: 'Saudi Arabia', label: 'First Saudi State (Diriyah)', start: 1727, end: 1818, flag: 'disputed', basis: 'Muhammad bin Saud takes Diriyah 1727, though the 1744 pact with Ibn ʿAbd al-Wahhab is as often given as the founding, to Ibrahim Pasha razing Diriyah in 1818' },
  { country: 'Saudi Arabia', label: 'Second Saudi State (Nejd)', start: 1824, end: 1891, flag: '', basis: 'Turki bin Abdullah retakes Riyadh 1824 to the Rashidi victory at al-Mulayda, 1891' },
  { country: 'Saudi Arabia', label: 'Unification (Ibn Saud)', start: 1902, end: 1932, flag: '', basis: 'Ibn Saud retakes Riyadh 15 Jan 1902 to the proclamation of the Kingdom, 23 Sept 1932' },
  { country: 'Saudi Arabia', label: 'Modern Saudi Arabia', start: 1932, end: null, flag: '', basis: 'Royal decree of 23 Sept 1932 unifying Hejaz and Najd' },
  { country: 'Yemen', label: 'Sabaean / Himyarite', start: -799, end: 570, flag: 'unsound', basis: 'Saba to the Aksumite and Sasanian conquests' },
  { country: 'Yemen', label: 'Islamic Yemen (Rasulid / Zaydi)', start: 897, end: 1962, flag: 'unsound', basis: 'Zaydi imamate at Saʿda to the 1962 republic' },
  { country: 'Yemen', label: 'First Ottoman Yemen', start: 1538, end: 1636, flag: '', basis: 'Ottoman arrival 1538 to the Qasimid imams driving them out entirely in 1635-36' },
  { country: 'Yemen', label: 'Qasimid Yemen (independent Zaydi)', start: 1636, end: 1849, flag: '', basis: 'Two centuries in which the north answered to no outside power: the Qasimid imamate from the Ottoman expulsion of 1636 to the Ottoman return to the Tihamah in 1849' },
  { country: 'Yemen', label: 'Second Ottoman Yemen', start: 1849, end: 1918, flag: 'disputed', basis: 'The Ottomans return to the Tihamah coast in 1849 but do not retake Sanaʿa until 1872, a 23-year spread on the start, and hold to the end of the First World War' },
  { country: 'Yemen', label: 'British Aden', start: 1839, end: 1967, flag: '', basis: 'Britain takes Aden, Jan 1839, to the withdrawal of 30 Nov 1967' },
  { country: 'Yemen', label: 'Modern Yemen', start: 1990, end: null, flag: 'disputed', basis: 'North–South unification, 22 May 1990' },
  { country: 'UAE', label: 'Magan (Bronze Age)', start: -2499, end: -1799, flag: 'disputed', basis: 'Umm an-Nar period; Magan named in cuneiform from c. −2300' },
  { country: 'UAE', label: 'Islamic era', start: 630, end: 1820, flag: 'unsound', basis: 'Muhammad\'s envoys reach the region to the General Maritime Treaty' },
  { country: 'UAE', label: 'Portuguese era', start: 1507, end: 1650, flag: 'disputed', basis: 'Albuquerque takes Julfar and Khor Fakkan 1507; the Yaʿrubids oust the Portuguese from Julfar and Dibba 1633 and Muscat 1650. Gulf-wide accounts run it from da Gama\'s 1498 voyage, so the start moves by nine years' },
  { country: 'UAE', label: 'Trucial States (British protection)', start: 1820, end: 1971, flag: 'disputed', basis: 'General Maritime Treaty of 1820, exclusive agreement 1892, to federation on 2 Dec 1971; the status was a protected state rather than a formal protectorate, which is the disputed part' },
  { country: 'UAE', label: 'Modern UAE', start: 1971, end: null, flag: '', basis: 'Federation established 2 Dec 1971' },
  { country: 'Qatar', label: 'Pearling / Bedouin Qatar', start: 1766, end: 1939, flag: 'disputed', basis: 'Al-Zubārah founded to the discovery of oil' },
  { country: 'Qatar', label: 'Ottoman Qatar', start: 1871, end: 1915, flag: '', basis: 'Ottoman garrison lands at Bidda, Dec 1871; evacuated the night of 19-20 Aug 1915' },
  { country: 'Qatar', label: 'British protection', start: 1916, end: 1971, flag: '', basis: 'Anglo-Qatari treaty of 3 Nov 1916 to independence, 3 Sept 1971' },
  { country: 'Qatar', label: 'Modern Qatar', start: 1971, end: null, flag: '', basis: 'Independence declared 3 Sept 1971' },
  { country: 'Kuwait', label: 'Pre-oil Kuwait (Bani Utub, pearling/trade)', start: 1752, end: 1946, flag: 'disputed', basis: 'Bani Utub choose a Ṣabāḥ sheikh to the first crude export' },
  { country: 'Kuwait', label: 'British protection', start: 1899, end: 1961, flag: '', basis: 'Anglo-Kuwaiti Agreement of 23 Jan 1899 to Britain\'s recognition of independence, 19 June 1961' },
  { country: 'Kuwait', label: 'Modern Kuwait', start: 1961, end: null, flag: '', basis: 'Britain recognises independence, 19 June 1961' },
  { country: 'Bahrain', label: 'Dilmun (Bronze Age)', start: -2199, end: -1599, flag: 'disputed', basis: 'Early Dilmun; Qalʿat al-Bahrain occupied from c. −2300' },
  { country: 'Bahrain', label: 'Islamic Bahrain', start: 628, end: 1783, flag: 'unsound', basis: 'Conversion of al-Mundhir ibn Sāwā to Āl Khalīfah rule' },
  { country: 'Bahrain', label: 'Portuguese Bahrain', start: 1521, end: 1602, flag: '', basis: 'António Correia takes Bahrain from the Jabrids 1521 to the Safavid conquest 1602' },
  { country: 'Bahrain', label: 'Safavid / Persian Bahrain', start: 1602, end: 1783, flag: 'disputed', basis: 'Safavid conquest 1602 to the Bani Utbah invasion 1783; Persian control lapses after Isfahan falls in 1722 and the island passes between Omani, Persian and Huwala hands' },
  { country: 'Bahrain', label: 'British protection', start: 1861, end: 1971, flag: 'disputed', basis: 'Perpetual Treaty of Peace and Friendship 1861 to independence 15 Aug 1971. 1892 is the stricter legal anchor - the exclusive agreement that made the status match the Trucial States - so the start moves by 31 years. Begun at 1861 to match the UAE row, which likewise starts at the first maritime treaty rather than at 1892' },
  { country: 'Bahrain', label: 'Modern Bahrain', start: 1971, end: null, flag: '', basis: 'Independence declared 15 Aug 1971' },
  { country: 'Oman', label: 'Magan (copper kingdom)', start: -2499, end: -1799, flag: 'disputed', basis: 'Umm an-Nar period; Magan the principal copper source' },
  { country: 'Oman', label: 'Ibadi Imamate', start: 750, end: 1959, flag: 'unsound', basis: 'First imamate after the Umayyad fall to the 1959 surrender' },
  { country: 'Oman', label: 'Portuguese Muscat', start: 1507, end: 1650, flag: '', basis: 'Albuquerque captures Muscat 1507 to the Yaʿrubid recapture 1650; the last garrison leaves Khasab 1656' },
  { country: 'Oman', label: 'Omani Empire (Zanzibar)', start: 1650, end: 1856, flag: 'disputed', basis: 'Yaʿrubids retake Muscat to the split on Saʿīd\'s death' },
  { country: 'Oman', label: 'Modern Oman', start: 1970, end: null, flag: '', basis: 'Accession of Qaboos bin Said — Oman was never formally colonised' },
  { country: 'Syria', label: 'Aramean / Classical antiquity', start: -1199, end: 636, flag: 'unsound', basis: 'Aramean emergence to the Byzantine defeat at Yarmūk' },
  { country: 'Syria', label: 'Umayyad Damascus', start: 661, end: 750, flag: '', basis: 'The Umayyad caliphate ruled from Damascus' },
  { country: 'Syria', label: 'Ottoman Syria', start: 1516, end: 1918, flag: '', basis: 'Marj Dābiq to the Ottoman withdrawal from Damascus' },
  { country: 'Syria', label: 'Modern Syria', start: 1946, end: null, flag: '', basis: 'French withdrawal completed April 1946' },
  { country: 'Syria', label: 'Mamluk Syria', start: 1260, end: 1516, flag: '', basis: 'Mamluk victory over the Mongols at Ain Jalut, 3 Sept 1260, brings Damascus and Aleppo under Cairo\'s rule within weeks, to the Ottoman victory at Marj Dābiq, 1516.' },
  { country: 'Syria', label: 'French Mandate', start: 1920, end: 1946, flag: '', basis: 'French victory at Maysalun, 24 July 1920, and the occupation of Damascus the next day end the Arab Kingdom of Syria and open the Mandate, to the completed French military withdrawal, 17 April 1946.' },
  { country: 'Lebanon', label: 'Phoenician city-states', start: -1199, end: -331, flag: 'disputed', basis: 'Iron Age independence of Tyre / Sidon / Byblos to Alexander\'s siege' },
  { country: 'Lebanon', label: 'Mount Lebanon (Maronite / Druze)', start: 1516, end: 1918, flag: 'unsound', basis: 'Maʿnid emirate through the Mutasarrifate' },
  { country: 'Lebanon', label: 'French Mandate', start: 1920, end: 1943, flag: '', basis: 'Greater Lebanon proclaimed to independence, 22 Nov 1943' },
  { country: 'Lebanon', label: 'Modern Lebanon', start: 1943, end: null, flag: '', basis: 'Independence proclaimed 22 Nov 1943' },
  { country: 'Lebanon', label: 'Crusader County of Tripoli', start: 1109, end: 1289, flag: '', basis: 'Crusader forces under Bertrand of Toulouse take Tripoli after a long siege, 12 July 1109, founding the county, to the Mamluk sultan Qalawun\'s conquest of the city, 27 April 1289.' },
  { country: 'Lebanon', label: 'Hellenistic Phoenicia (Ptolemaic & Seleucid)', start: -331, end: -63, flag: 'unsound', basis: 'After Alexander\'s death the Wars of the Diadochi leave Ptolemaic Egypt in control of the Phoenician coast by 301 BC, though fighting over it begins as early as 332 BC; the Seleucids seize Phoenicia from the Ptolemies at the Battle of Panion, 200 BC; ends when Pompey\'s conquest of Syria, 64 BC, brings it into the Roman province. Two rival Hellenistic dynasties split this label with the handover falling inside it, so no single year represents it.' },
  { country: 'Lebanon', label: 'Roman Berytus', start: -63, end: 330, flag: 'disputed', basis: 'Pompey\'s conquest of Syria, 64 BC, brings Berytus into Roman rule; Augustus refounds it as the colonia of Berytus for veterans of the V Macedonica and VIII Augusta legions only in 14 BC, a 50-year spread on when Roman Berytus properly begins - the city then builds the law school that became the most famous in the empire; ends at Constantine\'s dedication of Constantinople, 11 May 330.' },
  { country: 'Lebanon', label: 'Byzantine Lebanon', start: 330, end: 635, flag: 'disputed', basis: 'Constantine\'s dedication of Constantinople, 11 May 330, opens Byzantine rule; Berytus\'s law school, still the empire\'s most famous, is destroyed with most of the city in the earthquake and tsunami of 9 July 551, ending its centuries as a center of legal education though Byzantine administration continues; ends when Arab forces take Beirut during the Muslim conquest of the Levant, 635.' },
  { country: 'Lebanon', label: 'Early Islamic Lebanon', start: 635, end: 1109, flag: 'disputed', basis: 'Arab forces take Beirut in 635 during the Muslim conquest of the Levant, opening Rashidun, then Umayyad, Abbasid and Fatimid rule of the coast; ends with the Crusader capture of Tripoli, 12 July 1109 - though Beirut itself falls only the next year, 13 May 1110, and Sidon in December 1110, roughly a one-year spread depending which Lebanese city is meant.' },
  { country: 'Jordan', label: 'Nabataean (Petra)', start: -311, end: 106, flag: '', basis: 'Nabataeans attested to Trajan\'s annexation' },
  { country: 'Jordan', label: 'Islamic era', start: 636, end: 1918, flag: 'unsound', basis: 'Arab conquest to the end of Ottoman rule' },
  { country: 'Jordan', label: 'British Mandate (Transjordan)', start: 1921, end: 1946, flag: '', basis: 'Emirate of Transjordan established April 1921 to independence, 25 May 1946' },
  { country: 'Jordan', label: 'Modern Jordan', start: 1946, end: null, flag: '', basis: 'Treaty of London, independence 25 May 1946' },
  { country: 'Jordan', label: 'Roman & Byzantine Jordan (Provincia Arabia)', start: 106, end: 636, flag: 'disputed', basis: 'Trajan annexes the Nabataean kingdom as Provincia Arabia, 22 March 106; pagan Roman and Christian Byzantine administration both sit inside this one label, so the 371 midpoint falls in the Byzantine half; ends at the Arab victory at Yarmouk, 636.' },
  { country: 'Palestine', label: 'Canaanite / Philistine antiquity', start: -1999, end: -603, flag: 'unsound', basis: 'Middle Bronze city-states to the destruction of Philistia' },
  { country: 'Palestine', label: 'Roman Judea', start: -62, end: 135, flag: 'disputed', basis: 'Pompey takes Jerusalem 63 BC and the province of Iudaea is formed in AD 6 - the start moves by 69 years depending which you count - to Hadrian merging the provinces as Syria Palaestina after the Bar Kokhba revolt, 135. Rome did not call the region Palestine before that date' },
  { country: 'Palestine', label: 'Syria Palaestina / Byzantine', start: 135, end: 638, flag: 'disputed', basis: 'Hadrian\'s renaming in 135 through Constantine\'s Christianisation of the province to the Arab conquest of 638; pagan Rome and Christian Byzantium sit inside one label, so the midpoint represents the Byzantine half' },
  { country: 'Palestine', label: 'Islamic Palestine (Jund Filasṭīn)', start: 638, end: 1099, flag: 'disputed', basis: 'ʿUmar\'s capture of Jerusalem 638; the region is administered as Jund Filasṭīn, one of the ajnād of Bilād al-Shām, through Rashidun, Umayyad, Abbasid and Fatimid rule, to the Crusader capture of Jerusalem on 15 July 1099' },
  { country: 'Palestine', label: 'Crusader Kingdom of Jerusalem', start: 1099, end: 1291, flag: '', basis: 'First Crusade takes Jerusalem 15 July 1099 to the fall of Acre, 18 May 1291' },
  { country: 'Palestine', label: 'Mamluk Palestine', start: 1291, end: 1516, flag: '', basis: 'Mamluk rule from the fall of Acre 1291 to Marj Dābiq, 1516' },
  { country: 'Palestine', label: 'Ottoman Palestine', start: 1516, end: 1917, flag: 'disputed', basis: 'Marj Dābiq 1516 to Allenby entering Jerusalem, 11 Dec 1917; the four centuries between run through the Damascus and Beirut vilayets and the Sanjak of Jerusalem, so the administrative frame moves inside the label' },
  { country: 'Palestine', label: 'British Mandate', start: 1917, end: 1948, flag: 'disputed', basis: 'The start moves by six years depending on the instrument: OETA military rule from Dec 1917, civil administration 1 July 1920, League ratification 1922 and entry into force 1923. Ends with the Mandate\'s termination, 15 May 1948' },
  { country: 'Palestine', label: 'Nakba and after', start: 1948, end: 1967, flag: '', basis: 'The Mandate\'s termination and the Nakba, 15 May 1948, to the June 1967 war; the West Bank is administered by Jordan and Gaza by Egypt throughout' },
  { country: 'Palestine', label: 'Occupation (1967– )', start: 1967, end: null, flag: 'disputed', basis: 'The June 1967 war to THE STORY\'S OWN PRESENT - this row has no closing year because the occupation of the West Bank, Gaza and East Jerusalem has not ended. Oslo 1993 and the Palestinian Authority 1994 sit inside it, not after it', standing: 'The West Bank, Gaza and East Jerusalem remain under occupation, so this period has not closed.' },
  { country: 'Palestine', label: 'Modern Palestine', start: 1988, end: null, flag: 'disputed', basis: 'Declaration of Independence proclaimed at Algiers, 15 Nov 1988 - the founding act, as every other Modern row in this file uses one. 1948, 1964 and 1994 are all argued instead, a spread of 46 years, which is why this is flagged', standing: 'The West Bank, Gaza and East Jerusalem remain under occupation, so this period has not closed.' },
  { country: 'Morocco', label: 'Amazigh / Mauretania', start: -224, end: 44, flag: 'unsound', basis: 'Mauretanian kingdom to annexation by Claudius' },
  { country: 'Morocco', label: 'Idrisid (Islamization)', start: 788, end: 974, flag: 'disputed', basis: 'Idris I to the Idrisid expulsion' },
  { country: 'Morocco', label: 'Almoravid / Almohad', start: 1062, end: 1269, flag: 'unsound', basis: 'Almoravid rise to the fall of Almohad Marrakech' },
  { country: 'Morocco', label: 'French / Spanish Protectorate', start: 1912, end: 1956, flag: '', basis: 'Treaty of Fes, 30 March 1912, to independence, 2 March 1956' },
  { country: 'Morocco', label: 'Modern Morocco', start: 1956, end: null, flag: 'disputed', basis: 'End of the French and Spanish protectorates; the start is arguable at 1912 or 1666 because the list skips 1269-1956' },
  { country: 'Morocco', label: 'Roman Mauretania Tingitana', start: 44, end: 429, flag: '', basis: 'Claudius organizes Mauretania Tingitana as a Roman province, 44 AD, after suppressing the revolt following King Ptolemy\'s murder, to the Vandals\' crossing from Spain and landing in Mauretania, 429.' },
  { country: 'Morocco', label: 'Vandal & Byzantine Mauretania', start: 429, end: 711, flag: 'unsound', basis: 'The Vandals cross from Spain and overrun coastal Mauretania in 429, though their real hold on the far west is thin; Justinian\'s reconquest, complete by 534, restores only a Byzantine toehold at the fortress-port of Septem (Ceuta), with the interior held by independent Moorish kingdoms throughout; ends when Ceuta\'s governor, Count Julian, allies with Tariq ibn Ziyad for the 711 conquest of Spain. Two regimes over nearly three centuries sharing one coastal foothold, so no single year represents the label.' },
  { country: 'Morocco', label: 'Umayyad Morocco & Berber Revolt', start: 711, end: 788, flag: 'unsound', basis: 'Musa ibn Nusayr\'s forces reach Tangier and Ceuta submits by treaty, completing the conquest of the Maghreb al-Aqsa by 711; nominal Umayyad rule from Kairouan lasts only until the Kharijite-inspired Berber Revolt of 740 breaks central authority for good, fragmenting the region into rival principalities - the Barghawata confederacy, the Salihid emirate of Nekor, the Midrarid state at Sijilmasa founded 757 - until Idris I founds the Idrisid dynasty at Volubilis, 788. Conquest-era unity and post-revolt fragmentation sit inside one label, so no single year represents it.' },
  { country: 'Morocco', label: 'Marinid Sultanate', start: 1269, end: 1465, flag: '', basis: 'The Marinids, already established at Fez since 1248, take Marrakesh from the Almohads in 1269; the dynasty ends when the last sultan, Abd al-Haqq II, is killed in a popular revolt at Fez, 1465.' },
  { country: 'Morocco', label: 'Wattasid Sultanate', start: 1472, end: 1554, flag: '', basis: 'Muhammad al-Sheikh al-Wattasi is formally installed as sultan in 1472, following the Marinid collapse; the dynasty ends at the Battle of Tadla and the death of the last Wattasid, Ali Abu Hassun, 1554, as the Saadians take Fez for good.' },
  { country: 'Morocco', label: 'Saadi Sultanate', start: 1510, end: 1659, flag: 'disputed', basis: 'Muhammad al-Qa\'im is recognized by the tribes of the Sous in 1510, the conventional start, though the Saadians only take Marrakesh in 1524-25 and do not finally expel the Wattasids from Fez until 1554 - a real spread of over 40 years on when Saadi rule actually begins; ends with the assassination of the last sultan, Ahmad al-Abbas, amid civil war, 1659.' },
  { country: 'Morocco', label: 'Alaouite Morocco (pre-Protectorate)', start: 1666, end: 1912, flag: 'disputed', basis: 'Moulay al-Rashid captures Fez, 6 June 1666, and Marrakesh two years later, unifying Morocco under his family\'s rule - though the Alaouite line\'s own founding is dated to 1631, when his father Moulay Sharif first took power in Tafilalt, a 35-year spread on the start; ends with the Treaty of Fes establishing the French and Spanish protectorates, 30 March 1912.' },
  { country: 'Algeria', label: 'Numidia / Carthage-Rome', start: -813, end: 429, flag: 'unsound', basis: 'Traditional founding of Carthage to the Vandal crossing' },
  { country: 'Algeria', label: 'Ottoman Regency of Algiers', start: 1516, end: 1830, flag: '', basis: 'Aruj invited to Algiers to the French capture' },
  { country: 'Algeria', label: 'French Algeria', start: 1830, end: 1962, flag: '', basis: 'French conquest to independence' },
  { country: 'Algeria', label: 'Modern Algeria', start: 1962, end: null, flag: '', basis: 'Independence 1962' },
  { country: 'Algeria', label: 'Vandal & Byzantine Algeria', start: 429, end: 698, flag: 'unsound', basis: 'The label combines two separate foreign occupations with different capitals and armies: the Vandal Kingdom, from Genseric\'s crossing in 429 to Belisarius\'s reconquest in 533-34, and the Byzantine exarchate that replaces it, ending with the Arab capture of Carthage in 698 - no single year represents both regimes.' },
  { country: 'Algeria', label: 'Rustamid Imamate (Tahert)', start: 776, end: 909, flag: 'disputed', basis: 'Abd al-Rahman ibn Rustam is elected Ibadi imam at Tahert in 777 by most accounts, though some sources give 776 for his arrival and the town\'s founding, a small spread on the start; the Fatimids capture and raze Tahert, ending the imamate, 909.' },
  { country: 'Algeria', label: 'Fatimid & Zirid Algeria', start: 909, end: 1014, flag: 'unsound', basis: 'After destroying Rustamid Tahert in 909, the Fatimids claim the whole central Maghreb and, from 972, govern it through their Zirid vassals, who install the Sanhaja Hammadid line as local governors around Msila; this suzerainty ends only when Hammad ibn Buluggin breaks away and declares his own independence, 1014. Two overlapping distant suzerainties with no distinct Algerian administration of their own, so no single year represents the label.' },
  { country: 'Algeria', label: 'Hammadid Algeria', start: 1014, end: 1152, flag: 'disputed', basis: 'Hammad ibn Buluggin builds the fortress of Qal\'at Bani Hammad from 1007-08 and declares independence from the Zirids in 1014, a real spread on when Hammadid rule actually begins; ends when the Almohads storm Bejaia and the last emir, Yahya ibn Abd al-Aziz, surrenders, 10 November 1152.' },
  { country: 'Algeria', label: 'Zayyanid Kingdom of Tlemcen', start: 1235, end: 1554, flag: 'disputed', basis: 'Yaghmurasen ibn Zyan declares independence from the collapsing Almohads and founds the Kingdom of Tlemcen, 1235; the end unwinds over nearly 40 years - Ottoman forces first besiege Tlemcen in 1517, capture it outright in 1551 with the last sultan fleeing to Spanish Oran, and only formally absorb it as a beylik of the Regency of Algiers in 1556 - this row uses 1554, when Tlemcen becomes an Ottoman protectorate, roughly midway through that unwinding.' },
  { country: 'Tunisia', label: 'Carthage (Punic)', start: -813, end: -145, flag: '', basis: 'Founding to destruction in the Third Punic War' },
  { country: 'Tunisia', label: 'Ifriqiya (Aghlabid / Kairouan)', start: 800, end: 909, flag: '', basis: 'The Aghlabid dynasty at Kairouan' },
  { country: 'Tunisia', label: 'Ottoman / Husainid Beylik', start: 1574, end: 1881, flag: 'unsound', basis: 'Ottoman incorporation to the Treaty of Bardo' },
  { country: 'Tunisia', label: 'Modern Tunisia', start: 1956, end: null, flag: '', basis: 'Independence 1956, republic 1957' },
  { country: 'Tunisia', label: 'Hafsid Ifriqiya', start: 1229, end: 1574, flag: '', basis: 'Abu Zakariya Yahya declares independence from the Almohads at Tunis, 1229, to the Ottoman conquest of Tunis and the execution of the last Hafsid ruler, 1574.' },
  { country: 'Tunisia', label: 'French Protectorate', start: 1881, end: 1956, flag: '', basis: 'Treaty of Bardo, 12 May 1881, establishes the French protectorate, to independence, 20 March 1956.' },
  { country: 'Tunisia', label: 'Roman Africa (Africa Proconsularis)', start: -145, end: 439, flag: 'disputed', basis: 'Rome destroys Carthage and creates the province of Africa after its victory in the Third Punic War, 146 BC, though Augustus does not reorganize it as Africa Proconsularis until 27 BC, a 119-year spread on the start; ends when the Vandal king Genseric captures Carthage, 439.' },
  { country: 'Tunisia', label: 'Vandal Kingdom', start: 439, end: 534, flag: '', basis: 'Genseric captures Carthage in 439, founding the Vandal Kingdom; ends with Belisarius\'s decisive victory over the Vandals at Tricamarum, 15 December 533, and King Gelimer\'s surrender to the Byzantines the following year, 534.' },
  { country: 'Tunisia', label: 'Byzantine Africa (Exarchate of Carthage)', start: 534, end: 698, flag: '', basis: 'Byzantine reconquest is completed with Gelimer\'s surrender in 534, restoring Roman rule as the praetorian prefecture and later Exarchate of Africa; ends when Arab forces under Hasan ibn al-Nu\'man take Carthage for good, 698.' },
  { country: 'Tunisia', label: 'Fatimid & Zirid Ifriqiya', start: 909, end: 1229, flag: 'unsound', basis: 'The Fatimids conquer Aghlabid Kairouan in 909 and rule Ifriqiya directly until moving their capital to Cairo, 969-73, after which their Zirid vassals govern from Mahdia; the Zirids drift into practical independence around 1048, are devastated by the Hilalian Arab invasions of the 1050s, and lose the coast briefly to Norman Sicily (1148-1160) before the Almohads conquer Mahdia, January 1160; ends when the Hafsid governor Abu Zakariya declares independence from the Almohads, 1229. At least four regimes across three centuries, so no single year represents the label.' },
  { country: 'Libya', label: 'Garamantes / Greco-Roman', start: -999, end: 700, flag: 'unsound', basis: 'Envelope of the Fazzan Garamantian and the coastal Greco-Roman sequences' },
  { country: 'Libya', label: 'Ottoman / Karamanli (Tripoli)', start: 1551, end: 1911, flag: 'unsound', basis: 'Ottoman capture of Tripoli to the Italian occupation' },
  { country: 'Libya', label: 'Italian Libya', start: 1911, end: 1943, flag: '', basis: 'Italian occupation to the Allied expulsion of the Axis' },
  { country: 'Libya', label: 'Modern Libya', start: 1951, end: null, flag: '', basis: 'Independence declared 24 Dec 1951' },
  { country: 'Libya', label: 'Knights Hospitaller Tripoli', start: 1530, end: 1551, flag: '', basis: 'Charles V grants Tripoli to the Knights Hospitaller along with Malta and Gozo, 1530, to the Ottoman corsair Turgut Reis (Dragut) capturing the city, 15 Aug 1551.' },
  { country: 'Libya', label: 'Early Islamic Tripolitania', start: 700, end: 909, flag: 'unsound', basis: 'Arab governors continue Umayyad and then Abbasid rule over Tripolitania after the initial 643-44 conquest; Ibadi Kharijites seize Tripoli itself in 757 before the Abbasids retake it in 761; Aghlabid governors, appointed from 800, grow effectively autonomous; ends when the Fatimids topple the Aghlabid dynasty, 909. Umayyad governance, a Kharijite interlude and Aghlabid autonomy all sit inside this one label, so no single year represents it.' },
  { country: 'Libya', label: 'Fatimid, Zirid & Hafsid Tripolitania', start: 909, end: 1510, flag: 'unsound', basis: 'The Fatimids topple the Aghlabids in 909 and hold Tripoli directly before delegating Ifriqiya - Tripolitania included - to their Zirid vassals around 972; Zirid authority crumbles after the mid-11th-century Hilalian invasions and local rule passes to the Banu Khazrun emirate, interrupted by a Norman Sicilian occupation from 1143 to 1159; the Almohads retake the city in 1159-60, after which Hafsid Tunis claims often-nominal suzerainty from the 13th century; ends when a Spanish force under Pedro Navarro storms Tripoli, July 1510. At least five discontinuous regimes across six centuries, so no single year represents the label.' },
  { country: 'Libya', label: 'Spanish Tripoli', start: 1510, end: 1530, flag: '', basis: 'A Spanish force under Pedro Navarro storms and captures Tripoli, July 1510; Charles V grants the city to the Knights Hospitaller along with Malta and Gozo, a grant they accept 23 March 1530 and occupy that July.' },
  { country: 'Libya', label: 'British & French Military Administration', start: 1943, end: 1951, flag: 'disputed', basis: 'Free French forces occupy the Fezzan from January 1943; British forces take Tripolitania and Cyrenaica only after the Axis retreat, 13 May 1943, a four-month spread between the two zones\' starts; both administrations end together when Libya declares independence, 24 December 1951.' },
  { country: 'Mauritania', label: 'Sanhaja Berber / trans-Saharan', start: 700, end: 1040, flag: 'disputed', basis: 'Regular camel caravans to the start of the Sanhaja reform' },
  { country: 'Mauritania', label: 'Almoravid reform', start: 1040, end: 1147, flag: '', basis: 'Ibn Yasin\'s movement to the Almohad capture of Marrakesh' },
  { country: 'Mauritania', label: 'Modern Mauritania', start: 1960, end: null, flag: '', basis: 'Independence declared 28 Nov 1960' },
  { country: 'Mauritania', label: 'Emirate of Trarza', start: 1674, end: 1903, flag: 'disputed', basis: 'The Char Bouba war (1673-77) breaks Zawiya clerical power and installs the Hassani warrior emirate at its end, though some accounts trace Trarza\'s founding to Hassani conquests as early as the 1640s, a real spread on the start; ends when the emir accepts the French protectorate, 1903-04.' },
  { country: 'Mauritania', label: 'French Mauritania (Colonial)', start: 1904, end: 1960, flag: 'disputed', basis: 'Mauritania is organized as a French protectorate and civil territory, 1904, though Adrar in the north resists Gouraud\'s campaigns until 1912 and revolts continue to 1934, a real spread on when control was actually established; ends with independence, 28 Nov 1960.' },
  { country: 'Sudan', label: 'Kush / Meroë (Nubian)', start: -779, end: 350, flag: 'disputed', basis: 'Napatan emergence at el-Kurru to the last Meroitic royal burials' },
  { country: 'Sudan', label: 'Christian Nubia (Makuria)', start: 569, end: 1317, flag: 'disputed', basis: 'Makuria\'s conversion to the mosque conversion at Dongola' },
  { country: 'Sudan', label: 'Funj Sultanate (Sennar)', start: 1504, end: 1821, flag: '', basis: 'Foundation under Amara Dunqas to the submission of Badi VII' },
  { country: 'Sudan', label: 'Modern Sudan', start: 1956, end: null, flag: '', basis: 'End of the Condominium, independence 1 Jan 1956' },
  { country: 'Sudan', label: 'Turco-Egyptian Sudan (Turkiyya)', start: 1821, end: 1885, flag: 'disputed', basis: 'Muhammad Ali\'s invasion, launched from Cairo in July 1820, completes the conquest of riverine Sudan by 1821-22 and founds Khartoum as capital in May 1821, a real spread on the start; ends with the Mahdist capture of Khartoum, 26 Jan 1885.' },
  { country: 'Sudan', label: 'Mahdist State', start: 1885, end: 1899, flag: 'disputed', basis: 'Fall of Khartoum to the Mahdi, 26 Jan 1885; Kitchener\'s victory at Omdurman, 2 Sept 1898, breaks the state, but the Khalifa fights on until his death at Umm Diwaykarat, 24 Nov 1899, a 14-month spread on the end.' },
  { country: 'Sudan', label: 'Anglo-Egyptian Condominium', start: 1899, end: 1956, flag: '', basis: 'The Condominium Agreement, 19 Jan 1899, places Sudan under joint British-Egyptian rule, to independence, 1 Jan 1956.' },
  { country: 'Sudan', label: 'X-Group Nubia (Ballana Culture)', start: 350, end: 543, flag: 'disputed', basis: 'Meroitic royal power collapses by around 350 - the exact end is itself argued across a 320-350 range - into the archaeologically-defined \'X-Group\' culture centred on the Ballana royal necropolis; ends when the Byzantine missionary Julian converts the kingdom of Nobatia to Christianity, 543, the first of the three Nubian successor kingdoms to convert.' },
  { country: 'Sudan', label: 'Nubia in Transition (Dotawo & Dongola)', start: 1317, end: 1504, flag: 'unsound', basis: 'A Mamluk-installed Muslim king takes the throne room at Dongola in 1317, ending Christian Makuria\'s own royal line; a rump Christian state, called Dotawo in its own Old Nubian records, persists further upriver, but scholars dispute even its rough end - anywhere from about 1500 to, per 2023 reassessments, well into the 17th century - while the Funj Sultanate rises far to the south in 1504. No continuous single polity spans the interval, so no single year represents the label.' },
  { country: 'Somalia', label: 'Land of Punt / antiquity', start: -2499, end: -1159, flag: 'unsound', basis: 'Span of attested Egyptian contact with Punt — not a claim about Somali territory' },
  { country: 'Somalia', label: 'Islamic sultanates (Adal / Ajuran)', start: 1250, end: 1700, flag: 'unsound', basis: 'Ajuran attested to its collapse; Adal flourished 1415–1577' },
  { country: 'Somalia', label: 'Modern Somalia', start: 1960, end: null, flag: '', basis: 'Union as the Somali Republic, 1 July 1960' },
  { country: 'Somalia', label: 'British Somaliland', start: 1888, end: 1960, flag: '', basis: 'The British Somaliland protectorate is formally declared, 1888, to independence as the State of Somaliland, 26 June 1960, five days before union with the south.' },
  { country: 'Somalia', label: 'Italian Somaliland', start: 1889, end: 1960, flag: 'disputed', basis: 'Protectorate treaties with the sultans of Hobyo and the Majeerteen, 1889, though the Banaadir colony is not formally organized until 19 March 1905, a 16-year spread on the start; ends with independence and union with British Somaliland to form the Somali Republic, 1 July 1960.' },
  { country: 'Somalia', label: 'Geledi, Majeerteen & Hobyo Sultanates', start: 1695, end: 1927, flag: 'unsound', basis: 'Three separate, non-contiguous Somali sultanates: Geledi in the south, founded 1695 by some accounts (a scholarly \'c. 1750\' is also cited, a real spread), absorbed into Italian Somaliland by 1911; the Majeerteen sultanate in the northeast, whose own founding is placed anywhere from the 15th century to the 1800s, becoming an Italian protectorate in 1889; and Hobyo, founded in the 1870s or 1884 by Yusuf Ali Kenadid, also an Italian protectorate from 1889. All three are only fully extinguished by Italy\'s Campaign of the Sultanates, completed 1927, and their territory overlaps the British and Italian Somaliland rows above throughout. No single year represents polities founded up to two centuries apart.' },
  { country: 'Somalia', label: 'Dervish State', start: 1899, end: 1920, flag: 'disputed', basis: 'Sayyid Mohammed Abdullah Hassan preaches against British and Christian influence from 1895, but the Dervish State proper is usually dated from his 1899 declaration of jihad (1896 is also used for when the movement was organizing, a real spread on the start); it collapses when the RAF bombs the Dervish capital at Taleh, February 1920, though Hassan himself dies of illness the following year.' },
  { country: 'Djibouti', label: 'Adal / Afar-Somali sultanates', start: 1285, end: 1862, flag: 'unsound', basis: 'Walashma Ifat through Adal, Aussa and Tadjoura to the purchase of Obock' },
  { country: 'Djibouti', label: 'French Somaliland', start: 1896, end: 1967, flag: 'disputed', basis: 'Côte française des Somalis to its 1967 renaming' },
  { country: 'Djibouti', label: 'Modern Djibouti', start: 1977, end: null, flag: '', basis: 'Independence 27 June 1977' },
  { country: 'Djibouti', label: 'French Territory of the Afars and the Issas', start: 1967, end: 1977, flag: '', basis: 'French Somaliland is renamed the Territoire français des Afars et des Issas, 5 July 1967, to independence as Djibouti, 27 June 1977.' },
  { country: 'Comoros', label: 'Shirazi / Swahili sultanates', start: 1200, end: 1886, flag: 'unsound', basis: 'Attested sultanate towns to the French protectorate treaties' },
  { country: 'Comoros', label: 'French colonial', start: 1886, end: 1975, flag: '', basis: 'Protectorate treaties to independence, 6 July 1975' },
  { country: 'Comoros', label: 'Modern Comoros', start: 1975, end: null, flag: '', basis: 'Independence declared 6 July 1975' },
  { country: 'Andalusia (historical)', label: 'Umayyad Conquest of Iberia', start: 711, end: 756, flag: '', basis: 'Tariq ibn Ziyad crosses at Gibraltar and defeats King Roderic at Guadalete in 711, opening the Umayyad conquest of Hispania; the province governed for Damascus (and later Baghdad) ends when Abd al-Rahman I enters Córdoba on 14 May 756 and founds an independent emirate.' },
  { country: 'Andalusia (historical)', label: 'Emirate of Córdoba', start: 756, end: 929, flag: '', basis: 'Abd al-Rahman I founds the independent Umayyad Emirate at Córdoba on 14 May 756, severing al-Andalus from the Abbasid caliphate; it ends when Abd al-Rahman III proclaims himself Caliph on 16 January 929, elevating the emirate to a caliphate.' },
  { country: 'Andalusia (historical)', label: 'Caliphate of Córdoba', start: 929, end: 1031, flag: '', basis: 'Abd al-Rahman III\'s proclamation of the Caliphate in January 929 opens al-Andalus\'s imperial peak under him and al-Hakam II; it ends in 1031 when Córdoba\'s notables depose the last Umayyad caliph, Hisham III, amid the Fitna, abolishing the caliphate and fragmenting the state into taifa kingdoms.' },
  { country: 'Andalusia (historical)', label: 'Taifa Kingdoms', start: 1031, end: 1091, flag: '', basis: 'The Caliphate\'s abolition in 1031 splinters al-Andalus into roughly thirty rival taifa kingdoms (Seville, Toledo, Zaragoza, Granada among them); the period ends in 1091 when the Almoravids depose al-Mu\'tamid and annex Seville, the last major independent taifa, after being invited in to fight Castile at Sagrajas in 1086.' },
  { country: 'Andalusia (historical)', label: 'Almoravid al-Andalus', start: 1091, end: 1147, flag: 'disputed', basis: 'Dated from the Almoravid annexation of Seville in 1091, when Yusuf ibn Tashfin\'s forces absorbed the taifas outright; their military intervention actually began with the Battle of Sagrajas in 1086, a five-year gap depending on whether one counts the first campaign or formal rule. It ends in 1147 when the last Almoravid ruler, Ishaq ibn Ali, is killed at Marrakesh by the Almohads, who then take over in Iberia too. This is the Iberian wing of the same dynasty covered for Morocco by the existing Almoravid / Almohad row (1062-1269); dates here are set for al-Andalus specifically, not the Maghreb.' },
  { country: 'Andalusia (historical)', label: 'Almohad al-Andalus', start: 1147, end: 1228, flag: 'disputed', basis: 'Begins with the Almoravid collapse in 1147, though the Almohads did not complete their conquest of the peninsula\'s Muslim principalities until 1172, a 25-year gap between first foothold and full domination. It ends in October 1228 when the governor al-Ma\'mun abandons Seville for Morocco, ending Almohad rule in Iberia and opening the Third Taifa period. As with the prior row, this is the Iberian dating, separate from the Moroccan Almoravid / Almohad row already in the table.' },
  { country: 'Andalusia (historical)', label: 'Emirate of Granada', start: 1238, end: 1492, flag: 'disputed', basis: 'Muhammad I ibn al-Ahmar is sometimes dated from his proclamation as emir at Arjona on 16 July 1232, but he did not take Granada itself, the seat he made his capital and began fortifying as the Alhambra, until May 1238 — a six-year gap between the two defensible starts. The emirate ends when Muhammad XII (Boabdil) surrenders the city to the Catholic Monarchs on 2 January 1492, ending Muslim rule in Iberia.' },
  { country: 'Brazil', label: 'Pre-Columbian Brazil', start: null, end: 1500, flag: 'unsound', basis: 'Human presence in Brazil is unresolved: the Luzia skeleton is dated 11,243-11,710 years BP, nearby Monte Verde in southern Chile to 14,500 (arguably 18,500) years BP, and the disputed Pedra Furada site claims up to roughly 22,000-25,000 years BP. The span also covers hundreds of unrelated peoples (Tupi, Je, Arawak, Carib and more), so no single start year or midpoint represents one \'Pre-Columbian Brazil.\' End is set at Cabral\'s landfall, 22 April 1500.' },
  { country: 'Brazil', label: 'Portuguese Colonial Brazil', start: 1500, end: 1822, flag: 'disputed', basis: 'Pedro Alvares Cabral lands at Porto Seguro 22 April 1500, opening Portuguese rule; Pedro I\'s \'Cry of Ipiranga\' on 7 September 1822 is the conventional end (Portugal recognized independence in the Treaty of Rio de Janeiro, 29 August 1825). Brazil\'s legal status as a mere colony arguably ended earlier still: in 1815 it was elevated to a co-equal kingdom within the United Kingdom of Portugal, Brazil and the Algarves, so some historians close \'colonial\' Brazil seven years before political independence.' },
  { country: 'Brazil', label: 'Empire of Brazil', start: 1822, end: 1889, flag: '', basis: 'Pedro I declares independence at the Cry of Ipiranga, 7 September 1822, and is crowned Emperor; Marshal Deodoro da Fonseca deposes Pedro II and proclaims the Republic on 15 November 1889, ending the monarchy.' },
  { country: 'Brazil', label: 'Modern Brazil', start: 1822, end: null, flag: '', basis: 'Anchored at the Cry of Ipiranga, 7 September 1822, when Pedro I declared Brazil\'s independence from Portugal (recognized by Portugal in the Treaty of Rio de Janeiro, 29 August 1825) — the founding act of Brazil as a sovereign nation, distinct from its later changes of government in 1889 and 1985.' },
  { country: 'Brazil', label: 'Republic of Brazil', start: 1889, end: 1964, flag: '', basis: 'Runs from the Proclamation of the Republic, 15 November 1889, to the military coup that opens 31 March 1964 and drives President Joao Goulart into exile by 4 April. Spans the oligarchic Old Republic, the Vargas era (Revolution of 1930, 3 October-3 November 1930, and the Estado Novo dictatorship of 1937-45), and the populist democracy of 1946-64, all under the same republican constitutional name.' },
  { country: 'Brazil', label: 'Military Dictatorship', start: 1964, end: 1985, flag: '', basis: 'Opens with the coup of 31 March-1 April 1964 that topples Joao Goulart, and closes with the inauguration of civilian president Jose Sarney on 15 March 1985, ending 21 years of military rule (the new democratic Constitution followed on 5 October 1988).' },
  { country: 'China', label: 'Tang Dynasty', start: 618, end: 907, flag: '', basis: 'Li Yuan founds the Tang dynasty in 618 after the collapse of the Sui; it ends in 907 when the warlord Zhu Wen deposes the last emperor, Emperor Ai, and founds Later Liang, opening the Five Dynasties period.' },
  { country: 'China', label: 'Ming Dynasty', start: 1368, end: 1644, flag: 'disputed', basis: 'Zhu Yuanzhang founds the Ming in 1368 after driving out the Yuan. The Chongzhen Emperor\'s suicide as Beijing falls to Li Zicheng\'s rebels, 25 April 1644, is the conventional end, but Southern Ming loyalist courts persisted until the Qing executed the Prince of Gui, Zhu Youlang, in 1662 -- an 18-year gap some historians count as part of the dynasty.' },
  { country: 'China', label: 'Qing Dynasty', start: 1644, end: 1912, flag: '', basis: 'Manchu forces occupy Beijing and enthrone the Shunzhi Emperor in 1644 following the Ming collapse. Empress Dowager Longyu issues the abdication edict for the child emperor Puyi on 12 Feb 1912, ending the dynasty.' },
  { country: 'China', label: 'Treaty Port China', start: 1842, end: 1943, flag: 'disputed', basis: 'The Treaty of Nanjing, 29 Aug 1842, ends the First Opium War and opens the first treaty ports with extraterritorial privileges for foreign powers. The US and UK sign treaties relinquishing extraterritoriality on 11 Jan 1943, though France and others followed only later and the system did not fully vanish until the 1949 Communist revolution -- a 6-year-plus gap in when the era is said to close.' },
  { country: 'China', label: 'Republican China', start: 1912, end: 1949, flag: '', basis: 'The Republic is proclaimed 1 Jan 1912 with Sun Yat-sen as provisional president and formalized by the Qing abdication edict of 12 Feb 1912. Mainland rule ends when the People\'s Republic is proclaimed 1 Oct 1949 and the Nationalist government evacuates to Taipei that December.' },
  { country: 'China', label: 'Japanese occupation', start: 1931, end: 1945, flag: 'disputed', basis: 'Japan stages the Mukden Incident, 18 Sept 1931, and occupies Manchuria, founding Manchukuo in 1932, but full-scale war and occupation of core China begins only with the Marco Polo Bridge Incident, 7 July 1937 -- a 6-year gap in what \'occupation\' is taken to mean. Japan\'s surrender is announced 15 Aug 1945 and signed 2 Sept 1945.' },
  { country: 'China', label: 'Modern China', start: 1949, end: null, flag: '', basis: 'Mao Zedong proclaims the People\'s Republic of China from Tiananmen on 1 Oct 1949, founding the modern state; this open-ended row anchors to the story\'s present.' },
  { country: 'France', label: 'Roman Gaul', start: -57, end: 486, flag: '', basis: 'Caesar\'s Gallic Wars open in 58 BC with the campaigns against the Helvetii and Ariovistus; Roman rule in Gaul ends when Clovis defeats Syagrius, the last Gallo-Roman ruler, at the Battle of Soissons in 486.' },
  { country: 'France', label: 'Frankish & Capetian France', start: 486, end: 1453, flag: '', basis: 'Opens with Clovis\'s victory at Soissons in 486, founding the Frankish kingdom that runs through the Carolingian and Capetian dynasties; closes with the French victory at Castillon, 17 July 1453, which ends the Hundred Years\' War and English claims to the French crown.' },
  { country: 'France', label: 'Renaissance & Ancien Régime France', start: 1453, end: 1789, flag: '', basis: 'Begins with the 1453 end of the Hundred Years\' War and the consolidation of Valois royal power; ends 14 July 1789 when the Bastille falls and the absolute monarchy of the Ancien Régime collapses.' },
  { country: 'France', label: 'Revolutionary & Napoleonic France', start: 1789, end: 1815, flag: '', basis: 'Runs from the fall of the Bastille on 14 July 1789, through the First Republic and Napoleon\'s Empire, to his final defeat at Waterloo and second abdication in June 1815, when the Congress of Vienna restores the Bourbon monarchy.' },
  { country: 'France', label: '19th-Century France (Restoration to Empire)', start: 1815, end: 1870, flag: '', basis: 'Spans the 1815 Bourbon Restoration through the July Monarchy, the Second Republic and the Second Empire — several distinct regimes bundled under one menu era; ends when the Third Republic is proclaimed 4 September 1870, two days after Napoleon III\'s capture at Sedan.' },
  { country: 'France', label: 'Modern France', start: 1870, end: null, flag: 'disputed', basis: 'Anchored to the Third Republic\'s proclamation on 4 September 1870, the start of the durable republican order — interrupted only by the 1940-44 occupation — that continues through the Fourth and Fifth Republics. Three other founding acts are seriously argued: the fall of the Bastille, 14 July 1789; the First Republic\'s proclamation, 21 September 1792; and the Fifth Republic\'s constitution of 4 October 1958 — a spread of 169 years across the four candidates.' },
  { country: 'France', label: 'German Occupation of France', start: 1940, end: 1944, flag: '', basis: 'The Franco-German armistice is signed 22 June 1940 after the Battle of France, dividing the country between direct German occupation and the collaborationist Vichy regime; ends with the Liberation of Paris on 25 August 1944.' },
  { country: 'Germany', label: 'Germanic Tribes & East Francia', start: -57, end: 962, flag: '', basis: 'Opens in 58 BC when Caesar defeats Ariovistus\'s Suebi and fixes the Rhine as the Roman-Germanic frontier; runs through the Frankish conquests and the 843 Treaty of Verdun, which creates East Francia; ends 2 February 962, when Pope John XII crowns Otto I emperor, founding the Holy Roman Empire.' },
  { country: 'Germany', label: 'Medieval Germany (Holy Roman Empire)', start: 962, end: 1517, flag: '', basis: 'Begins 2 February 962 with Otto I\'s imperial coronation, founding the Holy Roman Empire of the German Nation; ends 31 October 1517, when Luther posts his Ninety-Five Theses at Wittenberg, opening the Reformation that fractures the Empire\'s religious unity.' },
  { country: 'Germany', label: 'Reformation & the Holy Roman Empire', start: 1517, end: 1806, flag: '', basis: 'Runs from Luther\'s Ninety-Five Theses of 31 October 1517, through the Peace of Augsburg, the Thirty Years\' War and the Peace of Westphalia, to 6 August 1806, when Francis II renounces the imperial title and dissolves the Holy Roman Empire under Napoleonic pressure.' },
  { country: 'Germany', label: 'Napoleonic Germany (Confederation of the Rhine)', start: 1806, end: 1815, flag: '', basis: 'Begins 12 July 1806, when sixteen German states form the French-sponsored Confederation of the Rhine days before the old Empire\'s dissolution; ends 8 June 1815, when the Congress of Vienna\'s German Federal Act replaces it with the German Confederation.' },
  { country: 'Germany', label: 'German Confederation & the Wars of Unification', start: 1815, end: 1871, flag: '', basis: 'Opens 8 June 1815 with the German Federal Act founding the loose 39-state German Confederation; covers the 1848 revolutions and Bismarck\'s wars of 1864, 1866 and 1870-71; ends 18 January 1871, when the German Empire is proclaimed at Versailles.' },
  { country: 'Germany', label: 'Modern Germany', start: 1871, end: null, flag: '', basis: 'Anchored to the German Empire\'s proclamation in the Hall of Mirrors at Versailles on 18 January 1871, the founding act of the unified German nation-state that persists — through the Weimar, Nazi, divided and reunified periods — into the present Federal Republic.' },
  { country: 'Germany', label: 'Allied Occupation & Divided Germany', start: 1945, end: 1990, flag: '', basis: 'Begins with Germany\'s unconditional surrender on 8 May 1945 and the four-power occupation formalized by the Berlin Declaration; covers the 1949 division into the Federal Republic and the German Democratic Republic; ends with reunification on 3 October 1990.' },
  { country: 'India', label: 'Maurya Empire', start: -321, end: -184, flag: '', basis: 'Chandragupta Maurya\'s conquest of the Nanda Empire founds the dynasty c. 322 BCE; Pushyamitra Shunga assassinates the last emperor, Brihadratha, in 185 BCE and founds the Shunga dynasty, ending Maurya rule outright.' },
  { country: 'India', label: 'Delhi Sultanate', start: 1206, end: 1526, flag: 'disputed', basis: 'Qutb al-Din Aibak is enthroned in Delhi in 1206 after Muhammad of Ghor\'s assassination, the conventional founding; some historians instead date it from Ghor\'s 1192 victory at the Second Battle of Tarain, moving the start back 14 years. Babur\'s victory over Ibrahim Lodi at Panipat, 21 April 1526, ends it.' },
  { country: 'India', label: 'Mughal Empire', start: 1526, end: 1857, flag: 'disputed', basis: 'Babur defeats Ibrahim Lodi at Panipat, 21 April 1526, founding the empire. Bahadur Shah II is captured and the throne abolished on 20 Sept 1857 during the Indian Rebellion, but his formal exile to Rangoon follows only after an 1858 trial, on 7 Oct 1858, so the end moves by about a year depending on which act is taken as final.' },
  { country: 'India', label: 'Company Raj', start: 1757, end: 1858, flag: 'disputed', basis: 'Clive\'s victory at Plassey, 23 June 1757, is the conventional start of Company dominance in Bengal, though the Company only gains the diwani (revenue authority) via the Treaty of Allahabad, 12 Aug 1765, an 8-year gap historians argue over. The Government of India Act, assented 2 Aug 1858, transfers rule to the Crown effective 1 Nov 1858, ending it.' },
  { country: 'India', label: 'British Raj', start: 1858, end: 1947, flag: '', basis: 'The Crown assumes direct rule under the Government of India Act, effective 1 Nov 1858, following the 1857-58 rebellion. The Indian Independence Act 1947 ends it at midnight, 15 Aug 1947.' },
  { country: 'India', label: 'Modern India', start: 1947, end: null, flag: '', basis: 'India becomes independent at midnight, 15 Aug 1947, under the Indian Independence Act 1947; this founding act anchors the country\'s open-ended present.' },
  { country: 'Iran / Persia', label: 'Achaemenid Empire', start: -549, end: -329, flag: '', basis: 'Cyrus the Great overthrows the Median Empire in 550 BC, founding Achaemenid rule; ends with the assassination of Darius III near Hecatompylus in July 330 BC, the year after Alexander\'s victory at Gaugamela in 331 BC.' },
  { country: 'Iran / Persia', label: 'Sasanian Empire', start: 224, end: 651, flag: 'disputed', basis: 'Ardashir I kills the last Parthian king, Artabanus IV, at the Battle of Hormozdgan in 224, founding Sasanian rule; imperial power effectively ends when Arab forces occupy the capital Ctesiphon in 637, following the Battle of al-Qadisiyyah in 636, though the last claimant, Yazdegerd III, survives as a fugitive until murdered near Merv in 651, a 14-year gap between the capital\'s fall and the last shah\'s death.' },
  { country: 'Iran / Persia', label: 'Arab Conquest of Persia', start: 636, end: 651, flag: '', basis: 'The decisive Battle of al-Qadisiyyah in 636 opens Mesopotamia and the Iranian plateau to the Rashidun armies; the conquest closes with the death of the last Sasanian claimant, Yazdegerd III, near Merv in 651, ending organized Persian resistance.' },
  { country: 'Iran / Persia', label: 'Mongol Ilkhanate', start: 1256, end: 1335, flag: 'disputed', basis: 'Hulagu Khan establishes Mongol rule over Iran in 1256, though some date the Ilkhanate instead from his capture of Baghdad and formal proclamation as ilkhan in 1258, a small but genuine gap between two commonly cited foundings. Ends with the death of the last effective ilkhan, Abu Sa\'id, in 1335, after which the state fragments among rival claimants.' },
  { country: 'Iran / Persia', label: 'Safavid Empire', start: 1501, end: 1722, flag: 'disputed', basis: 'Ismail I is crowned Shah in Tabriz in 1501, founding Safavid rule; Isfahan falls to Ghilzai Afghan besiegers on 23 October 1722, forcing Shah Sultan Husayn\'s abdication. Historians who count the restored, nominal Safavid shahs instead extend the dynasty to 1736, when Nader Shah deposes the puppet Abbas III, a 14-year gap between the effective and formal ends.' },
  { country: 'Iran / Persia', label: 'Pahlavi Iran', start: 1925, end: 1979, flag: '', basis: 'The Constituent Assembly deposes the last Qajar shah and names Reza Khan as Shah on 15 December 1925, founding the Pahlavi dynasty; ends when the monarchy is overthrown on 11 February 1979, the day the revolution\'s victory is marked.' },
  { country: 'Iran / Persia', label: 'Anglo-Soviet Occupation of Iran', start: 1941, end: 1946, flag: '', basis: 'British and Soviet forces invade neutral Iran on 25 August 1941, forcing Reza Shah\'s abdication weeks later; the occupation ends with the final Soviet withdrawal from Iranian Azerbaijan in May 1946, after Iran\'s complaint to the new UN Security Council.' },
  { country: 'Iran / Persia', label: 'Modern Iran', start: 1979, end: null, flag: '', basis: 'The Islamic Republic\'s founding act is the overthrow of the Pahlavi monarchy on 11 February 1979, ratified by the referendum that established the Islamic Republic on 1 April 1979.' },
  { country: 'Italy', label: 'Ancient Rome', start: -508, end: 476, flag: '', basis: 'Opens with the traditional founding of the Roman Republic in 509 BC after the expulsion of Tarquinius Superbus; ends 4 September 476 when Odoacer deposes Romulus Augustulus, conventionally marking the fall of the Western Roman Empire.' },
  { country: 'Italy', label: 'Medieval Italy', start: 476, end: 1347, flag: '', basis: 'Begins with the 476 fall of the Western Roman Empire and the peninsula\'s fragmentation among Ostrogoths, Byzantines, Lombards, Normans and communal city-states; ends with the Black Death\'s arrival at Messina in October 1347, the demographic watershed that closes the high medieval period.' },
  { country: 'Italy', label: 'Renaissance Italy (City-States)', start: 1347, end: 1494, flag: '', basis: 'Runs from the 1347-48 Black Death\'s demographic and cultural rupture through the Medici, Sforza and papal courts\' cultural flowering; ends when Charles VIII of France invades in September 1494, opening the Italian Wars and ending the city-states\' independent balance of power.' },
  { country: 'Italy', label: 'Italian Wars & Habsburg Domination', start: 1494, end: 1796, flag: '', basis: 'Opens with Charles VIII\'s 1494 invasion and the ensuing Italian Wars, settled by the 1559 Peace of Cateau-Cambrésis in favour of Spanish Habsburg control over Milan, Naples, Sicily and Sardinia, continued by the Austrian Habsburgs after the 1713-14 treaties of Utrecht and Rastatt; ends when Napoleon\'s victory at Montenotte, 12 April 1796, opens the French conquest of the peninsula.' },
  { country: 'Italy', label: 'Napoleonic Italy', start: 1796, end: 1815, flag: '', basis: 'Begins with Napoleon\'s victory at Montenotte, 12 April 1796, and the creation of French client republics and later the Kingdom of Italy and Kingdom of Naples; ends when the Congress of Vienna\'s Final Act, 9 June 1815, restores the pre-Napoleonic Italian states.' },
  { country: 'Italy', label: 'Risorgimento', start: 1815, end: 1861, flag: '', basis: 'Runs from the 1815 Vienna restoration of Austrian and Bourbon rule through Mazzini\'s, Cavour\'s and Garibaldi\'s unification movement and the wars of 1848-49, 1859 and 1860; ends when the Kingdom of Italy is proclaimed on 17 March 1861.' },
  { country: 'Italy', label: 'Modern Italy', start: 1861, end: null, flag: '', basis: 'Anchored to the Kingdom of Italy\'s proclamation on 17 March 1861 under Victor Emmanuel II. Venetia (1866) and Rome (captured 20 September 1870) were added afterward, but 17 March 1861 is the conventional founding act of the unified Italian state.' },
  { country: 'Korea', label: 'Three Kingdoms of Korea', start: -56, end: 668, flag: 'disputed', basis: 'The 12th-century Samguk sagi dates Silla\'s founding to 57 BCE, Goguryeo\'s to 37 BCE, and Baekje\'s to 18 BCE, but most modern historians place the three kingdoms\' emergence as true centralized states in the 2nd-3rd century CE, moving the start by several hundred years. The period undisputedly ends when the Silla-Tang alliance takes Pyongyang and destroys Goguryeo in 668.' },
  { country: 'Korea', label: 'Unified Silla', start: 668, end: 935, flag: 'disputed', basis: 'Goguryeo\'s fall in 668 conventionally opens Unified Silla, though Silla only fully expels Tang occupation forces from the peninsula by 676 after the Battle of Mount Maeso, an 8-year gap over when unification is complete. It ends when King Gyeongsun surrenders to Goryeo\'s Taejo in 935.' },
  { country: 'Korea', label: 'Goryeo Dynasty', start: 918, end: 1392, flag: 'disputed', basis: 'Wang Geon founds Goryeo in 918, but the peninsula is only fully unified after Silla\'s surrender in 935 and the conquest of Later Baekje in 936 -- an 18-year gap between the state\'s founding and its actual territorial reach. Yi Seong-gye\'s coup ends the dynasty in 1392, founding Joseon.' },
  { country: 'Korea', label: 'Joseon Dynasty', start: 1392, end: 1910, flag: 'disputed', basis: 'Yi Seong-gye founds Joseon in 1392. Gojong proclaims the Korean Empire in 1897, ending the \'Joseon\' name and status though the same royal house continues; some historians end \'Joseon\' there instead of at Japan\'s annexation on 29 Aug 1910, a 13-year gap.' },
  { country: 'Korea', label: 'Japanese colonial rule', start: 1910, end: 1945, flag: '', basis: 'The Japan-Korea Treaty is signed 22 Aug 1910 and proclaimed effective 29 Aug 1910, formally annexing Korea. Japan\'s surrender, announced 15 Aug 1945 and marked ever since as Korea\'s Liberation Day, ends colonial rule.' },
  { country: 'Korea', label: 'Liberation and Division', start: 1945, end: 1948, flag: '', basis: 'Japan\'s surrender on 15 Aug 1945 ends colonial rule and splits Korea at the 38th parallel under US and Soviet occupation zones. Formal statehood follows within the same year the row closes: the Republic of Korea proclaimed 15 Aug 1948, and the Democratic People\'s Republic of Korea on 9 Sept 1948.' },
  { country: 'Korea', label: 'Modern Korea', start: 1948, end: null, flag: 'disputed', basis: 'Statehood follows liberation within weeks in 1948: the Republic of Korea proclaimed 15 Aug 1948, the Democratic People\'s Republic of Korea on 9 Sept 1948, a 25-day gap this row cannot resolve at year granularity. Because the country string is simply \'Korea\', this open-ended row spans both the ROK and the DPRK continuously since 1948 without distinguishing which -- the writer must still choose a side once a year is set.' },
  { country: 'Mesopotamia (ancient)', label: 'Sumer', start: -2899, end: -2333, flag: 'disputed', basis: 'Early Dynastic Sumer runs from the archaeological onset of the walled city-states, conventionally 2900 BC, to Sargon of Akkad\'s conquest of Sumer, dated 2334 BC under the Middle Chronology; the Short Chronology places Sargon\'s rise nearer 2270 BC, moving the end by roughly 60 years, and 2900 BC is itself an archaeological convention rather than a single dated event.' },
  { country: 'Mesopotamia (ancient)', label: 'Akkadian Empire', start: -2333, end: -2153, flag: 'disputed', basis: 'Sargon of Akkad\'s conquest of Sumer founds the empire in 2334 BC; it collapses under Shu-turul around 2154 BC amid Gutian incursions. The Short Chronology dates the same reigns 2270-2083 BC, moving both boundaries by roughly 70-90 years, so the absolute calendar year is genuinely contested even though the sequence of kings is not.' },
  { country: 'Mesopotamia (ancient)', label: 'Babylon (Hammurabi\'s Empire)', start: -1893, end: -1594, flag: 'disputed', basis: 'Sumu-abum founds the First Dynasty of Babylon c. 1894 BC (Middle Chronology), the dynasty that produces Hammurabi\'s law code and empire; it ends when the Hittite king Mursili I sacks Babylon under Samsu-ditana, c. 1595 BC. The Short Chronology moves both dates by 64 years, to 1830 BC and 1531 BC, a gap large enough to matter for any dated setting.' },
  { country: 'Mesopotamia (ancient)', label: 'Assyrian Empire', start: -910, end: -608, flag: '', basis: 'Adad-nirari II\'s accession in 911 BC opens the Neo-Assyrian Empire\'s run of conquest from Nineveh; it ends with the fall of Harran in 609 BC, the last organized Assyrian resistance after Nineveh itself fell to the Medo-Babylonian coalition in 612 BC. First-millennium Assyrian dates rest on eponym lists and are fixed within a year or two.' },
  { country: 'Mesopotamia (ancient)', label: 'Neo-Babylonian Empire', start: -625, end: -538, flag: '', basis: 'Nabopolassar seizes Babylon and is crowned king in 626 BC, founding the Chaldean dynasty of Nebuchadnezzar II; it ends on 12 October 539 BC when Cyrus the Great\'s army enters Babylon unopposed and Nabonidus surrenders. Both dates are fixed by Babylonian chronicle tablets.' },
  { country: 'Mesopotamia (ancient)', label: 'Achaemenid Babylonia', start: -538, end: -330, flag: '', basis: 'Cyrus the Great\'s capture of Babylon in 539 BC brings Mesopotamia under Achaemenid Persian rule; it ends when Alexander the Great enters Babylon in October 331 BC, weeks after defeating Darius III at Gaugamela on 1 October 331 BC. This is the Persian conquest that closes the ancient Mesopotamian setting; no later row continues it.' },
  { country: 'Nigeria', label: 'Nok', start: -1499, end: 0, flag: 'disputed', basis: 'Modern archaeometric dating (thermoluminescence and radiocarbon work on the Samun Dukiya and Taruga sites) narrows the Nok culture\'s terracotta tradition to roughly 1500 BC to 1 BC, while older accounts built on earlier, less controlled fieldwork extended it to around 500 AD — a gap of up to 500 years on the end date, and no known political continuity links Nok to any later Nigerian state.' },
  { country: 'Nigeria', label: 'Kanem-Bornu Empire', start: 700, end: 1846, flag: 'disputed', basis: 'The founding of the Kanem state under the Duguwa/Sayfawa dynasty is typically dated to around 700 AD, but estimates in the literature range from c. 600 to c. 900; the earliest outside attestation is the Arab geographer al-Ya\'qubi\'s mention of Kanem in 872. The dynasty (which relocated its capital from Kanem to Bornu around 1380) ends in 1846, when mai Ali V Minargema is defeated and killed, closing the millennium-old office of mai.' },
  { country: 'Nigeria', label: 'Hausa City-States', start: 1000, end: 1804, flag: 'disputed', basis: 'Hausa oral tradition (the Bayajidda legend recorded in the Kano Chronicle) dates the founding of the Hausa Bakwai to around the 10th-11th century, while archaeological evidence for walled city-states like Kano and Katsina is firmer only from the 12th-14th century, a real range on the start. The era ends when Usman dan Fodio\'s jihad, declared against Sultan Yunfa of Gobir on 21 February 1804, topples the Hausa dynasties one by one; the last major capital, Alkalawa, fell in 1808, a further 4-year gap on the closing date.' },
  { country: 'Nigeria', label: 'Ife (Golden Age)', start: 1000, end: 1400, flag: 'disputed', basis: 'The Metropolitan Museum\'s chronology dates Ife\'s naturalistic terracotta and bronze court sculpture, and the sacred kingship it served, to 1000-1400 AD; other scholarship (World History Encyclopedia) places the same florescence in the 11th-15th century, moving the end boundary by up to a century depending on which chemical dating series is followed.' },
  { country: 'Nigeria', label: 'Benin Empire', start: 1180, end: 1897, flag: 'disputed', basis: 'Benin\'s regnal king-lists date the Oba dynasty\'s replacement of the earlier Ogiso monarchy to 1180 under Eweka I, though some reconstructions place his coronation nearer 1200; both rest on oral tradition rather than a contemporary written record, a roughly 20-year uncertainty. It ends in February 1897 when the British Punitive Expedition sacks Benin City and exiles Oba Ovonramwen, folding the kingdom into the Niger Coast Protectorate.' },
  { country: 'Nigeria', label: 'Sokoto Caliphate', start: 1804, end: 1903, flag: '', basis: 'Usman dan Fodio declares jihad against Sultan Yunfa of Gobir on 21 February 1804, founding the caliphate that comes to rule most of Hausaland and beyond; it ends when British forces accept Sokoto\'s surrender on 13 March 1903 and then kill Caliph Attahiru I in battle at Burmi that July, ending organized resistance.' },
  { country: 'Nigeria', label: 'British Colonial Nigeria', start: 1886, end: 1960, flag: '', basis: 'The Royal Niger Company receives its royal charter on 10 July 1886, beginning organized British rule over the Niger basin; Crown rule replaces the Company\'s in 1900 and the Northern and Southern Protectorates are amalgamated into one Nigeria on 1 January 1914, both falling inside this span, which ends at independence on 1 October 1960.' },
  { country: 'Nigeria', label: 'Modern Nigeria', start: 1960, end: null, flag: '', basis: 'Nigeria becomes independent of Britain on 1 October 1960, founding the modern federal state; this is the country\'s open-ended present-day row and so has no fixed end year.' },
  { country: 'Russia', label: 'Kievan Rus', start: 882, end: 1240, flag: 'disputed', basis: 'Oleg unites Novgorod and Kiev in 882, the conventional founding date; the Primary Chronicle\'s 862 date for Rurik\'s invitation to Novgorod is used by some accounts, but modern scholarship treats Rurik as semi-legendary and the 862 entry as a later chronicle construction, a 20-year gap between two defensible starts. Ends with the Mongol sack of Kiev, 6 December 1240.' },
  { country: 'Russia', label: 'Mongol / Tatar Yoke', start: 1240, end: 1480, flag: '', basis: 'Kiev falls to Batu Khan\'s Mongols on 6 December 1240, opening tributary subjugation to the Golden Horde; the Great Stand on the Ugra River, 8 October to 11 November 1480, ends the khan\'s demand for tribute and submission from Moscow\'s princes.' },
  { country: 'Russia', label: 'Muscovy', start: 1480, end: 1721, flag: '', basis: 'Begins where the 1480 Ugra standoff ends Mongol suzerainty over Moscow\'s grand princes (Ivan IV is crowned Tsar in 1547); runs through the Time of Troubles of 1598-1613, when a Polish garrison briefly held the Kremlin, to Peter I\'s proclamation of the Russian Empire after the Treaty of Nystad, ratified 10 September (30 August O.S.) 1721.' },
  { country: 'Russia', label: 'Russian Empire', start: 1721, end: 1917, flag: '', basis: 'Peter I takes the imperial title on 2 November (22 October O.S.) 1721, following the Treaty of Nystad; ends with Nicholas II\'s abdication during the February Revolution, 15 March (2 March O.S.) 1917.' },
  { country: 'Russia', label: 'Soviet Era', start: 1917, end: 1991, flag: 'disputed', basis: 'The Bolsheviks seize power in the October Revolution, 7 November (25 October O.S.) 1917; some historians instead date Soviet statehood from the formal Treaty on the Creation of the USSR, 30 December 1922, a 5-year gap between two defensible starts. Ends with Gorbachev\'s resignation, 25 December 1991, and the Supreme Soviet\'s dissolution declaration the next day.' },
  { country: 'Russia', label: 'Modern Russia', start: 1991, end: null, flag: '', basis: 'Deliberately anchored at 1991, not a round number: the Russian Federation\'s independent sovereignty follows the USSR\'s formal dissolution, marked by Gorbachev\'s resignation on 25 December and the Supreme Soviet\'s Declaration No. 142-N the following day, 26 December 1991.' },
  { country: 'Spain', label: 'Roman & Visigothic Hispania', start: -217, end: 711, flag: '', basis: 'Begins in 218 BC when Roman forces land at Empúries during the Second Punic War, opening the conquest of Hispania, and continues through the Visigothic kingdom established after Rome\'s collapse; ends with the Umayyad victory at Guadalete in 711, which destroys the Visigothic royal army.' },
  { country: 'Spain', label: 'Moorish Spain & the Reconquista', start: 711, end: 1492, flag: '', basis: 'Opens with the 711 Umayyad conquest that establishes al-Andalus, and covers its shrinking territory through the Caliphate of Córdoba, the Taifa kingdoms and the Nasrid Kingdom of Granada as Christian kingdoms advance from the north; ends 2 January 1492 when Granada, the last Muslim stronghold, surrenders to Ferdinand and Isabella.' },
  { country: 'Spain', label: 'Imperial Spain (Catholic Monarchs & Habsburgs)', start: 1492, end: 1700, flag: '', basis: 'Begins with Granada\'s fall and Spain\'s dynastic union under Ferdinand and Isabella in 1492, continuing through Charles I/V\'s accession in 1516, which brings the Habsburg dynasty and the American empire; ends 1 November 1700 with the death of the childless Charles II, extinguishing the Spanish Habsburg line.' },
  { country: 'Spain', label: 'Bourbon Spain (Empire, Enlightenment & the Peninsular War)', start: 1700, end: 1868, flag: '', basis: 'Opens with Charles II\'s death in 1700 and the War of the Spanish Succession that installs the Bourbon Philip V; the span includes the 1808-1813 French occupation under Joseph Bonaparte during the Peninsular War; ends with the September 1868 \'Glorious Revolution\' that overthrows Isabella II.' },
  { country: 'Spain', label: 'The Bourbon Restoration', start: 1874, end: 1931, flag: '', basis: 'Begins 29 December 1874 when General Martínez Campos\'s pronunciamiento proclaims Alfonso XII king, restoring the Bourbon monarchy after the First Republic and the Sexenio Democrático; ends 14 April 1931 with the proclamation of the Second Spanish Republic and Alfonso XIII\'s exile.' },
  { country: 'Spain', label: 'Franco\'s Spain', start: 1939, end: 1975, flag: 'disputed', basis: 'Franco\'s uncontested rule over all of Spain begins 1 April 1939 with the Nationalist victory in the Civil War; some date the regime instead from Franco\'s proclamation as Head of State on 1 October 1936, in the middle of the war — a three-year difference. Ends with Franco\'s death on 20 November 1975.' },
  { country: 'Spain', label: 'Modern Spain', start: 1978, end: null, flag: 'disputed', basis: 'Anchored to the Constitution ratified by popular referendum on 6 December 1978, which founded the current parliamentary monarchy. The other defensible founding act is Franco\'s death and Juan Carlos I\'s accession on 20-22 November 1975, three years earlier, marking the start of the Transition rather than its legal completion.' },
  { country: 'Turkey', label: 'Byzantine Anatolia', start: 330, end: 1071, flag: 'disputed', basis: 'Constantine dedicates Constantinople on 11 May 330, establishing Anatolia as the empire\'s core; the Battle of Manzikert, 26 August 1071, opens the interior to Turkic conquest and settlement. But Byzantine rule persisted in the west, ending only with the fall of Philadelphia in 1390, a roughly 319-year gap between two defensible ends for when Byzantine Anatolia truly closes.' },
  { country: 'Turkey', label: 'Seljuk Rum', start: 1077, end: 1308, flag: 'disputed', basis: 'Suleiman ibn Qutalmish founds the sultanate in 1077, seceding from the Great Seljuks; the line ends with the murder of the last sultan, Mesud II, in 1308. Real Seljuk sovereignty, however, breaks 65 years earlier at the Battle of Kosedag in 1243, when the sultanate becomes a Mongol tributary, a genuine dispute over when the era of independent Seljuk Rum actually ends.' },
  { country: 'Turkey', label: 'Ottoman Rise', start: 1299, end: 1453, flag: 'disputed', basis: '1299 is the traditional founding date for Osman\'s beylik, though no contemporary source survives from his reign; the first datable event of his life is the Battle of Bapheus in 1301/02, and some historians prefer Orhan\'s capture of Bursa on 6 April 1326 as the point a real Ottoman state existed, a 27-year range of defensible starts. Ends when Mehmed II takes Constantinople, 29 May 1453.' },
  { country: 'Turkey', label: 'Ottoman Golden Age', start: 1453, end: 1683, flag: '', basis: 'Begins with Mehmed II\'s capture of Constantinople on 29 May 1453; closes with the failed Second Siege of Vienna, 12 September 1683, whose territorial losses are formalized by the Treaty of Karlowitz in 1699.' },
  { country: 'Turkey', label: 'Late Ottoman Empire', start: 1683, end: 1922, flag: '', basis: 'Opens with the 1683 defeat at Vienna and the ensuing era of territorial contraction and reform (Tanzimat, then constitutional crises); ends when the Grand National Assembly abolishes the Sultanate on 1 November 1922.' },
  { country: 'Turkey', label: 'Modern Turkey', start: 1923, end: null, flag: '', basis: 'Founded by Mustafa Kemal\'s proclamation of the Republic on 29 October 1923, eleven months after the Sultanate\'s abolition and three months after the Treaty of Lausanne, 24 July 1923, secured international recognition.' },
  { country: 'United States', label: 'Pre-Columbian North America', start: null, end: 1492, flag: 'unsound', basis: 'Human arrival in North America is unresolved: White Sands, NM footprints are now independently dated to 21,000-23,000 years ago (Science, 2023 and confirmed 2025) against the older Clovis-first model of roughly 13,000 years, and hundreds of distinct, unrelated nations (Haudenosaunee, Lakota, Puebloan and more) existed across that span. No single start year or midpoint can represent one \'Indigenous North America,\' so this label carries no start and returns no anchor. End is set at Columbus\'s landfall, 12 October 1492, the conventional line separating \'pre-Columbian\' from contact, even though Columbus never reached the North American mainland.' },
  { country: 'United States', label: 'Colonial America', start: 1607, end: 1776, flag: 'disputed', basis: 'Jamestown, Virginia, founded 14 May 1607, is the conventional start of English colonial America, running to the Declaration of Independence on 4 July 1776. Spanish St. Augustine, Florida, founded September 1565, predates it by 42 years and is the oldest continuously occupied European settlement in the present United States, so the start moves depending on whether English or Spanish colonization is meant.' },
  { country: 'United States', label: 'American Revolution & Early Republic', start: 1776, end: 1789, flag: '', basis: 'Runs from the Declaration of Independence, 4 July 1776, through the war and the Articles of Confederation, to the new federal government convening under the ratified Constitution on 4 March 1789 and George Washington\'s inauguration on 30 April 1789.' },
  { country: 'United States', label: 'Modern United States', start: 1776, end: null, flag: 'disputed', basis: 'Anchored at the Declaration of Independence, 4 July 1776, the traditional birthdate of the nation. The alternative founding act is the Constitution taking effect 4 March 1789 (Washington inaugurated 30 April 1789), when the current federal government actually began, 13 years later; both are seriously argued as \'the\' founding.' },
  { country: 'United States', label: 'Civil War Era', start: 1861, end: 1865, flag: '', basis: 'Confederate batteries open fire on Fort Sumter 12 April 1861; Robert E. Lee surrenders to Ulysses S. Grant at Appomattox Court House 9 April 1865, effectively ending the war (the last Confederate field army, under Kirby Smith, surrendered 2 June 1865).' },
  { country: 'United States', label: 'Old West', start: 1865, end: 1890, flag: 'disputed', basis: 'Conventionally bounded by Appomattox, 9 April 1865, which opens mass westward settlement, and the 1890 census finding that underlay Frederick Jackson Turner\'s 1893 \'closing of the frontier\' thesis. Many historians instead open it at the 1848 Treaty of Guadalupe Hidalgo and California Gold Rush, 17 years earlier, and close it at the 1912 statehood of Arizona and New Mexico, the last contiguous territories, 22 years later.' },
  { country: 'United States', label: 'The Great Depression & WWII', start: 1929, end: 1945, flag: '', basis: 'Opens with the Wall Street Crash (\'Black Tuesday\'), 29 October 1929, and closes with Japan\'s formal surrender aboard USS Missouri, 2 September 1945, spanning the Dust Bowl, the New Deal, and American involvement in the Second World War.' },
];

/** The same half-away-from-zero rule `yearsToDays` uses, so a boundary year cannot land on two
 *  different anchors depending on which code path computed it. */
/**
 * NON-FINITE INPUT NOW YIELDS 0, WHICH IS A CHANGE. Before the rounding rule was shared, this
 * function had no finiteness guard and propagated NaN; it now inherits roundHalfAwayFromZero's
 * guard and returns 0. Zero is year 0 — a confident answer — so this function is NOT the place
 * that refuses. `anchorYearForEra` screens `presentYear` with Number.isFinite before it ever gets
 * here, and start/end come from the typed table, so no caller can reach it with junk. Any FUTURE
 * caller must screen its own inputs rather than reading a 0 as an anchor.
 */
export function midpointYear(start: number, end: number): number {
  return roundHalfAwayFromZero((start + end) / 2);
}

export interface AnchorVerdict {
  /** The year to use, or null when this file refuses to name one. */
  year: number | null;
  /** Empty when nothing needs saying. Otherwise the sentence shown beside the Present year box. */
  note: string;
  /**
   * A refusal and a miss are NOT the same thing, and a caller must not treat them alike.
   *
   * 'missing' — this country/label is not in the map at all (an unrecognised or renamed label, or
   *   a non-finite `presentYear`). A SUPPORTED STATE: FALL THROUGH to the generic band and then the
   *   current year, exactly as a miss has always meant.
   * 'refused' — the row IS in the map, but this file will not anchor it (no sourced start, or an
   *   unsound label naming more than one period). STOP AND ASK THE USER for a year. Falling through
   *   here manufactures exactly the approximation those rows exist to refuse.
   * 'ok' — a year was named, disputed boundary or not.
   */
  status: 'ok' | 'missing' | 'refused';
}

const NOT_FOUND: AnchorVerdict = { year: null, note: '', status: 'missing' };

export function findEraRow(country: string, label: string): EraRow | null {
  const c = String(country == null ? '' : country).trim();
  const l = String(label == null ? '' : label).trim();
  if (!c || !l) return null;
  return COUNTRY_ERA_YEARS.find((r) => r.country === c && r.label === l) || null;
}

/**
 * The anchor year for a chosen country + era, or a refusal with its reason.
 * `presentYear` is the current calendar year, used only to close an open-ended modern row.
 */
/** Appends a row's standing disclosure to whatever the flag produced. PURE, NEVER THROWS. */
function withStanding(row: EraRow, note: string): string {
  const standing = row && typeof row.standing === 'string' ? row.standing.trim() : '';
  if (!standing) return note;
  return note ? note + ' ' + standing : standing;
}

export function anchorYearForEra(country: string, label: string, presentYear: number): AnchorVerdict {
  if (!Number.isFinite(presentYear)) return NOT_FOUND;
  const row = findEraRow(country, label);
  if (!row) return NOT_FOUND;
  if (row.start === null) {
    return {
      year: null,
      status: 'refused',
      note: withStanding(row, `"${row.label}" has no sourced start, so there is no midpoint to take. Set the year you mean.`),
    };
  }
  if (row.flag === 'unsound') {
    return {
      year: null,
      status: 'refused',
      note: withStanding(row, `"${row.label}" covers more than one period, so there is no typical year for it. `
        + `Set the year you mean. (${describeRange(row, presentYear)})`),
    };
  }
  // AN OPEN-ENDED ROW ANCHORS AT THE PRESENT, NOT AT ITS MIDPOINT.
  // `end: null` means "through to the story's own present", so picking it IS picking now. Taking
  // the midpoint of founding..now answered a 250-year span with its centre: "Modern United States"
  // returned 1901, "Modern Britain" 1888, "Modern Egyptian" 1916 - a century out on the commonest
  // choice in the whole menu. The midpoint rule is right for a CLOSED period and wrong for an open
  // one, so the two cases are now distinguished. Edo Japan still anchors 1735.
  const year = row.end === null ? presentYear : midpointYear(row.start, row.end);
  if (row.flag === 'disputed') {
    return { year, status: 'ok', note: withStanding(row, `Dated ${describeRange(row, presentYear)}; that boundary is disputed. Change it if you mean otherwise.`) };
  }
  return { year, status: 'ok', note: withStanding(row, '') };
}

/** The band fallback, for a country with no deep timeline. */
export function anchorYearForBand(bandId: string, presentYear: number): number | null {
  if (!Number.isFinite(presentYear)) return null;
  const b = ERA_BANDS.find((x) => x.id === String(bandId || '').trim());
  if (!b) return null;
  if (b.offset !== undefined) return presentYear + b.offset;
  if (b.start === null || b.end === null) return null;
  return midpointYear(b.start, b.end);
}

/** "1750-2026", with BC printed by `1 - astronomicalYear` because there is no year zero. */
export function describeRange(row: EraRow, presentYear: number): string {
  if (!row || typeof row !== 'object') return '';
  const one = (y: number) => (y <= 0 ? `${1 - y} BC` : String(y));
  const start = row.start === null || row.start === undefined ? '?' : one(row.start);
  const end = row.end === null || row.end === undefined ? String(presentYear) : one(row.end);
  return `${start}–${end}`;
}

/** An era offset in days for a scene dated by period rather than by phrase. Refused rows give null. */
export function eraOffsetForEra(country: string, label: string, storyYear: number, presentYear: number): number | null {
  const v = anchorYearForEra(country, label, presentYear);
  if (v.year === null || !Number.isFinite(storyYear)) return null;
  return yearsToDays(v.year - storyYear);
}
