import { Module } from '@nestjs/common';
import { PrismaModule } from '../common/prisma/prisma.module';
import { ProjectsController } from './projects/projects.controller';
import { ProjectsService } from './projects/projects.service';
import { BudgetController } from './budget/budget.controller';
import { BudgetService } from './budget/budget.service';
import { CrewController } from './crew/crew.controller';
import { CrewService } from './crew/crew.service';
import { CallSheetsController } from './callsheets/callsheets.controller';
import { CallSheetsService } from './callsheets/callsheets.service';
import { PerDiemController } from './perdiem/perdiem.controller';
import { PerDiemService } from './perdiem/perdiem.service';
import { OveragesController } from './overages/overages.controller';
import { OveragesService } from './overages/overages.service';
import { CreditsController } from './credits/credits.controller';
import { CreditsService } from './credits/credits.service';
import { LedgerController } from './ledger/ledger.controller';
import { LedgerService } from './ledger/ledger.service';
import { CostingController } from './costing/costing.controller';
import { CostingService } from './costing/costing.service';
import { SchedulingController } from './scheduling/scheduling.controller';
import { SchedulingService } from './scheduling/scheduling.service';
import { DoodCalculationService } from './scheduling/dood-calculation.service';
import { CalendarAnchoringService } from './scheduling/calendar-anchoring.service';
import { BreakdownController } from './breakdown/breakdown.controller';
import { BreakdownService } from './breakdown/breakdown.service';
import { ScriptImportService } from './breakdown/script-import.service';
import { PayrollController } from './payroll/payroll.controller';
import { PayrollService } from './payroll/payroll.service';
import { LocationsController } from './locations/locations.controller';
import { LocationsService } from './locations/locations.service';
import { LocationNeedsController } from './locations/location-needs.controller';
import { LocationNeedsService } from './locations/location-needs.service';
import { ScoutVisitsController } from './locations/scout-visits.controller';
import { ScoutVisitsService } from './locations/scout-visits.service';
import { ClearancePacksController, ClearancePacksPublicController } from './locations/clearance-packs.controller';
import { ClearancePacksService } from './locations/clearance-packs.service';
import { LocationReportsController } from './locations/location-reports.controller';
import { LocationReportsService } from './locations/location-reports.service';
import { SunPathController } from './locations/sun-path.controller';
import { SunPathService } from './locations/sun-path.service';
import { ScriptReadinessController } from './locations/script-readiness.controller';
import { ScriptReadinessService } from './locations/script-readiness.service';
import { ScriptController } from './script/script.controller';
import { ScriptService } from './script/script.service';
import { AnnotationsController } from './script/annotations.controller';
import { AnnotationsService } from './script/annotations.service';
import { ScriptTransferService } from './script/script-transfer.service';
import { ScriptExportService } from './script/script-export.service';
import { ScriptProcurementService } from './script/script-procurement.service';
import { SidesController } from './script/sides.controller';
import { SidesService } from './script/sides.service';
import { LiningController } from './script/lining.controller';
import { LiningService } from './script/lining.service';
import { MasterScriptController } from './script/master-script.controller';
import { MasterScriptService } from './script/master-script.service';
import { ScriptAnalyzeController } from './script/script-analyze.controller';
import { ScriptAnalyzeService } from './script/script-analyze.service';
import { AudioEnginesController, VoiceCastingController, PronunciationController, RenderController, LayersController, AudioShareController, AudioSharePublicController } from './script/audio/script-audio.controller';
import { AudioEnginesService } from './script/audio/audio-engines.service';
import { VoiceCastingService } from './script/audio/voice-casting.service';
import { PronunciationService } from './script/audio/pronunciation.service';
import { RenderService } from './script/audio/render.service';
import { LayersService } from './script/audio/layers.service';
import { AudioShareService } from './script/audio/audio-share.service';
import { DocumentsController } from './documents/documents.controller';
import { DocumentsService } from './documents/documents.service';
import { MailController } from './mail/mail.controller';
import { MailService } from './mail/mail.service';
import { EmailService } from '../collections/email.service';
import { VendorOnboardingController, VendorOnboardingPublicController } from './vendor-onboarding/vendor-onboarding.controller';
import { VendorOnboardingService } from './vendor-onboarding/vendor-onboarding.service';
import { MovieMagicController } from './movie-magic/movie-magic.controller';
import { MovieMagicService } from './movie-magic/movie-magic.service';
import { DynamicContextService } from './context/dynamic-context.service';
import { AiMappingService } from './movie-magic/ai-mapping.service';
import { WorkflowModule } from '../workflow/workflow.module';
import { LocationsLibraryModule } from '../locations-library/locations-library.module';
import { TravelController } from './travel/travel.controller';
import { TravelService } from './travel/travel.service';
import { AmadeusService } from './travel/integrations/amadeus.service';
import { ConcurService } from './travel/integrations/concur.service';
import { ContractsController, ContractsWebhookController } from './contracts/contracts.controller';
import { ContractsService } from './contracts/contracts.service';
import { CastingController, CastingPublicController } from './casting/casting.controller';
import { CastingService } from './casting/casting.service';
import { AccommodationController } from './logistics/accommodation.controller';
import { AccommodationService } from './logistics/accommodation.service';
import { TransportController } from './logistics/transport.controller';
import { TransportService } from './logistics/transport.service';
import { ShuttleController } from './logistics/shuttle.controller';
import { ShuttleService } from './logistics/shuttle.service';
import { ArrivalController } from './logistics/arrival.controller';
import { ArrivalService } from './logistics/arrival.service';
import { LogisticsReportsController } from './logistics/logistics-reports.controller';
import { LogisticsReportsService } from './logistics/logistics-reports.service';

@Module({
  imports: [PrismaModule, WorkflowModule, LocationsLibraryModule],
  controllers: [ProjectsController, BudgetController, CrewController, CallSheetsController, PerDiemController, OveragesController, CreditsController, LedgerController, CostingController, SchedulingController, BreakdownController, DocumentsController, MailController, PayrollController, LocationsController, LocationNeedsController, ScoutVisitsController, ClearancePacksController, ClearancePacksPublicController, LocationReportsController, SunPathController, ScriptReadinessController, ScriptController, AnnotationsController, SidesController, LiningController, MasterScriptController, ScriptAnalyzeController, AudioEnginesController, VoiceCastingController, PronunciationController, RenderController, LayersController, AudioShareController, AudioSharePublicController, VendorOnboardingController, VendorOnboardingPublicController, MovieMagicController, TravelController, ContractsController, ContractsWebhookController, CastingController, CastingPublicController, AccommodationController, TransportController, ShuttleController, ArrivalController, LogisticsReportsController],
  providers: [ProjectsService, BudgetService, CrewService, CallSheetsService, PerDiemService, OveragesService, CreditsService, LedgerService, CostingService, SchedulingService, DoodCalculationService, CalendarAnchoringService, BreakdownService, ScriptImportService, DocumentsService, MailService, EmailService, PayrollService, LocationsService, LocationNeedsService, ScoutVisitsService, ClearancePacksService, LocationReportsService, SunPathService, ScriptReadinessService, ScriptService, AnnotationsService, ScriptTransferService, ScriptExportService, ScriptProcurementService, SidesService, LiningService, MasterScriptService, ScriptAnalyzeService, AudioEnginesService, VoiceCastingService, PronunciationService, RenderService, LayersService, AudioShareService, VendorOnboardingService, MovieMagicService, DynamicContextService, AiMappingService, TravelService, AmadeusService, ConcurService, ContractsService, CastingService, AccommodationService, TransportService, ShuttleService, ArrivalService, LogisticsReportsService],
  exports: [DynamicContextService, AiMappingService],
})
export class ProductionModule {}
